## create disease gene lists

In [1]:
import scanpy as sc
import pandas as pd
import numpy as np

In [2]:
adata=sc.read_h5ad("/scratch200/reutj/data/updated_cortex_data_hg38.h5ad")

In [3]:
import mygene

mg = mygene.MyGeneInfo()

In [2]:
microcephaly=pd.read_csv("/scratch200/reutj/data/severe_microcephaly_genes.csv")

In [3]:
microcephaly

,Entity Name,Entity type,Gene Symbol,Sources(; separated),Level4,Level3,Level2,Model_Of_Inheritance,Phenotypes,Omim,...,Position GRCh38 Start,Position GRCh38 End,STR Repeated Sequence,STR Normal Repeats,STR Pathogenic Repeats,Region Haploinsufficiency Score,Region Triplosensitivity Score,Region Required Overlap Percentage,Region Variant Type,Region Verbose Name
0,AARS,gene,AARS,Expert Review Green;Expert list,Severe microcephaly,NaN,NaN,"BIALLELIC, autosomal or pseudoautosomal","Developmental and epileptic encephalopathy 29,...",601065,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ACBD6,gene,ACBD6,Expert Review Green;NHS GMS,Severe microcephaly,NaN,NaN,"BIALLELIC, autosomal or pseudoautosomal",Neurodevelopmental disorder with progressive m...,616352,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ADARB1,gene,ADARB1,Expert Review Green;Literature,Severe microcephaly,NaN,NaN,"BIALLELIC, autosomal or pseudoautosomal","Neurodevelopmental disorder with hypotonia, mi...",601218,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ANKLE2,gene,ANKLE2,Expert Review Green;NHS GMS;Other,Severe microcephaly,NaN,NaN,"BIALLELIC, autosomal or pseudoautosomal","Microcephaly 16, primary, autosomal recessive,...",616062,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AP4E1,gene,AP4E1,Expert Review Green;Expert list,Severe microcephaly,NaN,NaN,"BIALLELIC, autosomal or pseudoautosomal","Spastic paraplegia 51, autosomal recessive, OM...",607244,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,ISCA-37408-Loss,region,NaN,NHS GMS;Expert Review Green;ClinGen,Severe microcephaly,NaN,NaN,"MONOALLELIC, autosomal or pseudoautosomal, imp...","Dysmorphic features, moderate to severe intell...",NaN,...,58912065.0,62261736.0,NaN,NaN,NaN,3.0,NaN,60.0,cnv_loss,2p15p16.1 region (includes BCL11A) Loss
271,ISCA-37425-Gain,region,NaN,NHS GMS;Expert Review Green;ClinGen,Severe microcephaly,NaN,NaN,"MONOALLELIC, autosomal or pseudoautosomal, imp...","Microcephaly, short stature and developmental ...",NaN,...,176301976.0,177620792.0,NaN,NaN,NaN,NaN,3.0,60.0,cnv_gain,5q35 recurrent (Sotos syndrome) region (includ...
272,ISCA-37501-Loss,region,NaN,NHS GMS;Expert Review Green;Expert list,Severe microcephaly,NaN,NaN,"MONOALLELIC, autosomal or pseudoautosomal, imp...","Chromosome 17q23.1-q23.2 deletion syndrome, 61...",NaN,...,60035641.0,62198448.0,NaN,NaN,NaN,3.0,NaN,60.0,cnv_loss,"17q23.1q23.2 recurrent region (includes TBX2, ..."
273,ISCA-46742-Loss,region,NaN,ClinGen;Expert Review Green,Severe microcephaly,NaN,NaN,"MONOALLELIC, autosomal or pseudoautosomal, imp...",NaN,NaN,...,5497217.0,5760091.0,NaN,NaN,NaN,3.0,NaN,60.0,cnv_loss,7p22.1 region (includes ACTB) Loss
274,ISCA-46743-Loss,region,NaN,Expert Review Amber;ClinGen,Severe microcephaly,NaN,NaN,"X-LINKED: hemizygous mutation in males, monoal...",NaN,NaN,...,123900469.0,124102669.0,NaN,NaN,NaN,3.0,NaN,60.0,cnv_loss,Xq25 region (includes STAG2) Loss

In [6]:
res=pd.DataFrame(mg.querymany(microcephaly["Gene Symbol"], scopes='symbol', fields='ensembl.gene', species='human'))
res

Input sequence provided is already in string format. No operation performed
Input sequence provided is already in string format. No operation performed
17 input query terms found no hit:	['AARS', 'CENPJ', 'HIST1H4C', 'IARS', 'KIF1BP', 'NARS', 'SARS', 'SPATA5L1', 'C7orf43', 'QARS', 'nan'

      query notfound    _id     _score                      ensembl
0      AARS     True    NaN        NaN                          NaN
1     ACBD6      NaN  84320  17.640953  {'gene': 'ENSG00000230124'}
2    ADARB1      NaN    104  18.159405  {'gene': 'ENSG00000197381'}
3    ANKLE2      NaN  23141  17.044762  {'gene': 'ENSG00000176915'}
4     AP4E1      NaN  23431  17.569900  {'gene': 'ENSG00000081014'}
..      ...      ...    ...        ...                          ...
270     nan     True    NaN        NaN                          NaN
271     nan     True    NaN        NaN                          NaN
272     nan     True    NaN        NaN                          NaN
273     nan     True    NaN        NaN                          NaN
274     nan     True    NaN        NaN                          NaN

[275 rows x 5 columns]

In [7]:
#function to gather the hits for each gene together 
dup_dict={}
for i in range(len(res)):
    gene=res['query'][i]
    dup_dict[gene]=[]
for i in range(len(res)):
    gene=res['query'][i]
    ens=res.ensembl[i]
    if type(ens)==dict:
        dup_dict[gene].append(ens['gene'])
    elif type(ens)==list:
        dup_dict[gene]=ens

dup_dict

{'AARS': [],
 'ACBD6': ['ENSG00000230124'],
 'ADARB1': ['ENSG00000197381'],
 'ANKLE2': ['ENSG00000176915'],
 'AP4E1': ['ENSG00000081014'],
 'ARF3': ['ENSG00000134287'],
 'ARPC4': ['ENSG00000241553'],
 'ASPM': ['ENSG00000066279'],
 'ATP1A2': ['ENSG00000018625'],
 'ATP6V0A1': ['ENSG00000033627'],
 'ATP6V0C': ['ENSG00000185883'],
 'ATR': ['ENSG00000175054'],
 'ATRX': ['ENSG00000085224'],
 'BLM': ['ENSG00000197299'],
 'BPTF': ['ENSG00000171634'],
 'BRCA2': ['ENSG00000139618'],
 'BRIP1': ['ENSG00000136492'],
 'BUB1': ['ENSG00000169679'],
 'BUB1B': ['ENSG00000156970'],
 'CAMK2B': ['ENSG00000058404'],
 'CAMSAP1': ['ENSG00000130559'],
 'CASK': ['ENSG00000147044'],
 'CCND2': ['ENSG00000118971'],
 'CDK5RAP2': ['ENSG00000136861'],
 'CDT1': ['ENSG00000167513'],
 'CENPF': ['ENSG00000117724'],
 'CENPJ': [],
 'CEP135': ['ENSG00000174799'],
 'CEP152': ['ENSG00000103995'],
 'CEP55': ['ENSG00000138180'],
 'CEP57': ['ENSG00000166037'],
 'CHAMP1': ['ENSG00000198824'],
 'CHKA': ['ENSG00000110721'],
 'CIT': ['ENSG00000122966'],
 'CKAP2L': ['ENSG00000169607'],
 'COASY': ['ENSG00000068120'],
 'CREBBP': ['ENSG00000005339'],
 'CSNK2A1': ['ENSG00000101266'],
 'CTCF': ['ENSG00000102974'],
 'CTNNB1': ['ENSG00000168036'],
 'CTU2': ['ENSG00000174177'],
 'DDX11': ['ENSG00000013573'],
 'DHCR7': ['ENSG00000172893'],
 'DIAPH1': ['ENSG00000131504'],
 'DNA2': ['ENSG00000138346'],
 'DNMT3A': ['ENSG00000119772'],
 'DOHH': ['ENSG00000129932'],
 'DONSON': ['ENSG00000159147'],
 'DPM1': ['ENSG00000000419'],
 'DROSHA': ['ENSG00000113360'],
 'DYNC1I2': [{'gene': 'ENSG00000292102'}, {'gene': 'ENSG00000077380'}],
 'DYRK1A': ['ENSG00000157540'],
 'EFTUD2': ['ENSG00000108883'],
 'EIF2S3': ['ENSG00000130741'],
 'EIF5A': [{'gene': 'ENSG00000132507'}, {'gene': 'ENSG00000288145'}],
 'ERCC4': ['ENSG00000175595'],
 'ERCC6': ['ENSG00000225830'],
 'ERCC8': ['ENSG00000049167'],
 'FANCA': ['ENSG00000187741'],
 'FANCB': ['ENSG00000181544'],
 'FANCC': ['ENSG00000158169'],
 'FANCD2': ['ENSG00000144554'],
 'FANCE': ['ENSG00000112039'],
 'FANCF': ['ENSG00000183161'],
 'FANCG': ['ENSG00000221829'],
 'FANCI': ['ENSG00000140525'],
 'FANCL': ['ENSG00000115392'],
 'FBRSL1': ['ENSG00000112787'],
 'FOXG1': ['ENSG00000176165'],
 'GINS3': ['ENSG00000181938'],
 'GMNN': ['ENSG00000112312'],
 'GPT2': ['ENSG00000166123'],
 'GRM7': ['ENSG00000196277'],
 'GTF2E2': ['ENSG00000197265'],
 'HDAC8': ['ENSG00000147099'],
 'HHAT': [{'gene': 'ENSG00000054392'}, {'gene': 'ENSG00000280680'}],
 'HIST1H4C': [],
 'HMGB1': ['ENSG00000189403'],
 'HPDL': ['ENSG00000186603'],
 'IARS': [],
 'IER3IP1': ['ENSG00000134049'],
 'IGF1': ['ENSG00000017427'],
 'IGF1R': ['ENSG00000140443'],
 'INTS11': ['ENSG00000127054'],
 'KIF11': ['ENSG00000138160'],
 'KIF14': ['ENSG00000118193'],
 'KIF1BP': [],
 'KMT2B': ['ENSG00000272333'],
 'KNL1': ['ENSG00000137812'],
 'LAGE3': ['ENSG00000196976'],
 'LARP7': ['ENSG00000174720'],
 'LIG4': ['ENSG00000174405'],
 'LMNB1': ['ENSG00000113368'],
 'LMNB2': ['ENSG00000176619'],
 'MCPH1': ['ENSG00000147316'],
 'MECP2': ['ENSG00000169057'],
 'METTL5': ['ENSG00000138382'],
 'MFSD2A': ['ENSG00000168389'],
 'MINPP1': ['ENSG00000107789'],
 'MORC2': ['ENSG00000133422'],
 'MSMO1': ['ENSG00000052802'],
 'MYCN': ['ENSG00000134323'],
 'NAPB': ['ENSG00000125814'],
 'NARS': [],
 'NBN': ['ENSG00000104320'],
 'NCAPD2': ['ENSG00000010292'],
 'NCAPD3': ['ENSG00000151503'],
 'NDE1': [{'gene': 'ENSG00000072864'}, {'gene': 'ENSG00000275911'}],
 'NHEJ1': ['ENSG00000187736'],
 'NIPBL': ['ENSG00000164190'],
 'NSD2': ['ENSG00000109685'],
 'NSRP1': ['ENSG00000126653'],
 'NUP107': ['ENSG00000111581'],
 'NUP188': ['ENSG00000095319'],
 'NUP214': ['ENSG00000126883'],
 'ORC1': ['ENSG00000085840'],
 'ORC4': ['ENSG00000115947'],
 'ORC6': ['ENSG00000091651'],
 'OSGEP': [{'gene': 'ENSG00000291794'}, {'gene': 'ENSG00000092094'}],
 'PCDH12': ['ENSG00000113555'],
 'PCNT': ['ENSG00000160299'],
 'PDHA1': ['ENSG00000131828'],
 'PLK4': ['ENSG00000142731'],
 'PNKP': ['ENSG00000039650'],
 'POC1A': ['ENSG00000164087'],
 'POGZ': ['ENSG00000143442'],
 'PPFIBP1': ['ENSG00000110841'],
 'PPIL1': ['ENSG00000137168'],
 'PQBP1': [{'gene': 'ENSG00000102103'}, {'gene': 'ENSG00000292208'}],
 'PRIM1': ['ENSG00000198056'],
 'PRUNE1': ['ENSG00000143363'],
 'PTPN23': ['ENSG00000076201'],
 'PUF60': ['ENSG00000179950'],
 'PUS7': ['ENSG00000091127'],
 'RAD21': ['ENSG00000164754'],
 'RAD50': ['ENSG00000113522'],
 'RAD51': ['ENSG00000051180'],
 'RBBP8': ['ENSG00000101773'],
 'RNU4-2': ['ENSG00000202538'],
 'RNU4ATAC': ['ENSG00000264229'],
 'RPL10': ['ENSG00000147403'],
 'RTTN': ['ENSG00000176225'],
 'SARS': [],
 'SASS6': ['ENSG00000156876'],
 'SLC1A4': ['ENSG00000115902'],
 'SLC25A19': ['ENSG00000125454'],
 'SLC38A3': ['ENSG00000188338'],
 'SLC9A6': ['ENSG00000198689'],
 'SLF2': ['ENSG00000119906'],
 'SLX4': ['ENSG00000188827'],
 'SMARCA5': ['ENSG00000153147'],
 'SMC1A': ['ENSG00000072501'],
 'SMC3': ['ENSG00000108055'],
 'SMC5': ['ENSG00000198887'],
 'SMG8': ['ENSG00000167447'],
 'SPATA5L1': [],
 'STAMBP': ['ENSG00000124356'],
 'STIL': ['ENSG00000123473'],
 'SVBP': ['ENSG00000177868'],
 'TMX2': ['ENSG00000213593'],
 'TNPO2': ['ENSG00000105576'],
 'TOP3A': [{'gene': 'ENSG00000177302'}, {'gene': 'ENSG00000284238'}],
 'TP53RK': ['ENSG00000172315'],
 'TRAIP': ['ENSG00000183763'],
 'TRAPPC10': ['ENSG00000160218'],
 'TRAPPC12': [{'gene': 'ENSG00000274891'}, {'gene': 'ENSG00000171853'}],
 'TRAPPC6B': ['ENSG00000182400'],
 'TRAPPC9': ['ENSG00000167632'],
 'TRIO': ['ENSG00000038382'],
 'TRMT10A': ['ENSG00000145331'],
 'TSEN15': ['ENSG00000198860'],
 'TSEN54': ['ENSG00000182173'],
 'TTC5': [{'gene': 'ENSG00000136319'}, {'gene': 'ENSG00000291781'}],
 'TTI1': ['ENSG00000101407'],
 'TUBG1': ['ENSG00000131462'],
 'TUBGCP2': ['ENSG00000130640'],
 'TUBGCP4': ['ENSG00000137822'],
 'TUBGCP6': ['ENSG00000128159'],
 'UBA5': ['ENSG00000081307'],
 'UFC1': ['ENSG00000143222'],
 'UFM1': ['ENSG00000120686'],
 'UGP2': ['ENSG00000169764'],
 'UNC80': ['ENSG00000144406'],
 'VRK1': ['ENSG00000100749'],
 'WDR11': ['ENSG00000120008'],
 'WDR37': ['ENSG00000047056'],
 'WDR4': ['ENSG00000160193'],
 'WDR62': ['ENSG00000075702'],
 'WDR73': [{'gene': 'ENSG00000177082'}, {'gene': 'ENSG00000291629'}],
 'WLS': ['ENSG00000116729'],
 'XRCC4': ['ENSG00000152422'],
 'YIPF5': ['ENSG00000145817'],
 'ZEB2': ['ENSG00000169554'],
 'ZNF335': ['ENSG00000198026'],
 'ZNF526': ['ENSG00000167625'],
 'AGMO': ['ENSG00000187546'],
 'AKT3': [{'gene': 'ENSG00000117020'}, {'gene': 'ENSG00000275199'}],
 'AP4B1': ['ENSG00000134262'],
 'AP4M1': ['ENSG00000221838'],
 'AP4S1': ['ENSG00000100478'],
 'ARCN1': ['ENSG00000095139'],
 'ATP9A': ['ENSG00000054793'],
 'BRD4': ['ENSG00000141867'],
 'C7orf43': [],
 'CCDC88A': ['ENSG00000115355'],
 'COG3': ['ENSG00000136152'],
 'COPB1': ['ENSG00000129083'],
 'CPSF3': ['ENSG00000119203'],
 'CRIPT': ['ENSG00000119878'],
 'ERCC5': ['ENSG00000134899'],
 'EXOC7': ['ENSG00000182473'],
 'FILIP1': ['ENSG00000118407'],
 'FRA10AC1': ['ENSG00000148690'],
 'LHX2': ['ENSG00000106689'],
 'MCM7': ['ENSG00000166508'],
 'MED11': ['ENSG00000161920'],
 'MED17': ['ENSG00000042429'],
 'MPLKIP': ['ENSG00000168303'],
 'MRE11': ['ENSG00000020922'],
 'NAA20': ['ENSG00000173418'],
 'PALB2': ['ENSG00000083093'],
 'PCDHGC4': ['ENSG00000242419'],
 'PDCD6IP': ['ENSG00000170248'],
 'PPP1R15B': ['ENSG00000158615'],
 'PSMC3': ['ENSG00000165916'],
 'QARS': [],
 'RAD51C': ['ENSG00000108384'],
 'RMI1': ['ENSG00000178966'],
 'RRP7A': ['ENSG00000189306'],
 'TAF13': ['ENSG00000197780'],
 'TRA2B': ['ENSG00000136527'],
 'TRIP13': ['ENSG00000071539'],
 'UBE3A': ['ENSG00000114062'],
 'VPS50': ['ENSG00000004766'],
 'YIF1B': ['ENSG00000167645'],
 'ZNF668': ['ENSG00000167394'],
 'ATP11A': ['ENSG00000068650'],
 'ATRIP': ['ENSG00000164053'],
 'CDC6': ['ENSG00000094804'],
 'CDK6': ['ENSG00000105810'],
 'CENPE': ['ENSG00000138778'],
 'CEP63': ['ENSG00000182923'],
 'COPB2': ['ENSG00000184432'],
 'DPP6': ['ENSG00000130226'],
 'EOMES': ['ENSG00000163508'],
 'FANCM': ['ENSG00000187790'],
 'GINS2': ['ENSG00000131153'],
 'HIKESHI': ['ENSG00000149196'],
 'NCAPH': ['ENSG00000121152'],
 'NIN': ['ENSG00000100503'],
 'NSMCE2': ['ENSG00000156831'],
 'NUF2': ['ENSG00000143228'],
 'PCLO': ['ENSG00000186472'],
 'PHC1': ['ENSG00000111752'],
 'PLAA': ['ENSG00000137055'],
 'PPP1R35': ['ENSG00000160813'],
 'RING1': [{'gene': 'ENSG00000231115'},
  {'gene': 'ENSG00000228520'},
  {'gene': 'ENSG00000235107'},
  {'gene': 'ENSG00000204227'},
  {'gene': 'ENSG00000206287'},
  {'gene': 'ENSG00000226788'}],
 'RUSC2': ['ENSG00000198853'],
 'SMO': ['ENSG00000128602'],
 'TCF4': ['ENSG00000196628'],
 'TPR': ['ENSG00000047410'],
 'TPRKB': [{'gene': 'ENSG00000291480'}, {'gene': 'ENSG00000144034'}],
 'TRMT1': ['ENSG00000104907'],
 'TUBGCP3': [{'gene': 'ENSG00000126216'}, {'gene': 'ENSG00000282003'}],
 'WDFY3': ['ENSG00000163625'],
 'ZNHIT3': [{'gene': 'ENSG00000278574'}, {'gene': 'ENSG00000273611'}],
 'ZPR1': ['ENSG00000109917'],
 'CTSF': ['ENSG00000174080'],
 'nan': []}

### little changes
* missing ensg:
AARS-> AARS1- ENSG00000090861 <br>
CENPJ-> CPAP- ENSG00000151849 <br>
'HIST1H4C'->H4C3 -ENSG00000197061 <br>
 'IARS'->IARS1- ENSG00000196305 <br>
'KIF1BP'->KIFBP-ENSG00000198954<br>
'NARS'-> NARS1-ENSG00000134440<br>
'SARS'->SARS1-ENSG00000031698<br>
'SPATA5L1'->AFG2B-ENSG00000171763<br>
'C7orf43'->TRRAPC14- ENSG00000146826<br>
* multiple ensg:<br>
'DYNC1I2',-ENSG00000077380<br>
'EIF5A',ENSG00000132507 <br>
'HHAT',ENSG00000054392<br>
'NDE1'ENSG00000072864<br>
,'OSGEP', ENSG00000092094<br>
'PQBP1'ENSG00000102103 <br>
,'TOP3A',ENSG00000177302<br>
'TRAPPC12'ENSG00000171853<br>
,'TTC5', ENSG00000136319 <br>
'WDR73', ENSG00000177082<br>
'AKT3',ENSG00000117020<br>
'TPRKB',ENSG00000144034<br>
'TUBGCP3',ENSG00000126216<br>
'ZNHIT3' ENSG00000273611

In [14]:
microcephaly_df1=pd.DataFrame.from_dict(dup_dict,orient='index').iloc[:268,:1]#drop last nan line
microcephaly_df1=microcephaly_df1.rename(columns={0:'ens'})
microcephaly_df1

                                 ens
AARS                            None
ACBD6                ENSG00000230124
ADARB1               ENSG00000197381
ANKLE2               ENSG00000176915
AP4E1                ENSG00000081014
...                              ...
TUBGCP3  {'gene': 'ENSG00000126216'}
WDFY3                ENSG00000163625
ZNHIT3   {'gene': 'ENSG00000278574'}
ZPR1                 ENSG00000109917
CTSF                 ENSG00000174080

[268 rows x 1 columns]

In [21]:
#change everything
microcephaly_df1.loc[microcephaly_df1.index=="AARS",'ens']= "ENSG00000090861"
microcephaly_df1.loc[microcephaly_df1.index=="CENPJ",'ens']="ENSG00000151849"
microcephaly_df1.loc[microcephaly_df1.index=="HIST1H4C",'ens']="ENSG00000197061"
microcephaly_df1.loc[microcephaly_df1.index=="IARS",'ens']="ENSG00000196305"
microcephaly_df1.loc[microcephaly_df1.index=="KIF1BP",'ens']="ENSG00000198954"
microcephaly_df1.loc[microcephaly_df1.index=="NARS",'ens']="ENSG00000134440"
microcephaly_df1.loc[microcephaly_df1.index=="SARS",'ens']="ENSG00000031698"
microcephaly_df1.loc[microcephaly_df1.index=='SPATA5L1','ens']="ENSG00000171763"
microcephaly_df1.loc[microcephaly_df1.index=='C7orf43','ens']="ENSG00000146826"
microcephaly_df1.loc[microcephaly_df1.index=='DYNC1I2','ens']="ENSG00000077380"
microcephaly_df1.loc[microcephaly_df1.index=='EIF5A','ens']="ENSG00000132507"
microcephaly_df1.loc[microcephaly_df1.index=='HHAT','ens']="ENSG00000054392"
microcephaly_df1.loc[microcephaly_df1.index=='NDE1','ens']="ENSG00000072864"
microcephaly_df1.loc[microcephaly_df1.index=='OSGEP','ens']="ENSG00000092094"
microcephaly_df1.loc[microcephaly_df1.index=='TOP3A','ens']="ENSG00000177302"
microcephaly_df1.loc[microcephaly_df1.index=='TRAPPC12','ens']="ENSG00000171853"
microcephaly_df1.loc[microcephaly_df1.index=='TTC5','ens']="ENSG00000136319"
microcephaly_df1.loc[microcephaly_df1.index=='WDR73','ens']="ENSG00000177082"
microcephaly_df1.loc[microcephaly_df1.index=='AKT3','ens']="ENSG00000117020"
microcephaly_df1.loc[microcephaly_df1.index=='TPRKB','ens']="ENSG00000144034"
microcephaly_df1.loc[microcephaly_df1.index=='TUBGCP3','ens']="ENSG00000126216"
microcephaly_df1.loc[microcephaly_df1.index=='ZNHIT3','ens']="ENSG00000273611"
microcephaly_df1.loc[microcephaly_df1.index=='RING1','ens']='ENSG00000231115'

In [25]:
microcephaly_df2=pd.DataFrame({'gene':microcephaly_df1.index,'ens':microcephaly_df1.ens}).reset_index()
microcephaly_df2=microcephaly_df2.drop(columns='index')
microcephaly_df2

        gene              ens
0       AARS  ENSG00000090861
1      ACBD6  ENSG00000230124
2     ADARB1  ENSG00000197381
3     ANKLE2  ENSG00000176915
4      AP4E1  ENSG00000081014
..       ...              ...
263  TUBGCP3  ENSG00000126216
264    WDFY3  ENSG00000163625
265   ZNHIT3  ENSG00000273611
266     ZPR1  ENSG00000109917
267     CTSF  ENSG00000174080

[268 rows x 2 columns]

In [26]:
#just change names that are difenr than gencards annotations
microcephaly_df2.loc[microcephaly_df2.gene=="AARS",'gene']= "AARS1"
microcephaly_df2.loc[microcephaly_df2.gene=="CENPJ",'gene']= "CPAP"
microcephaly_df2.loc[microcephaly_df2.gene=="IARS",'gene']= "IARS1"
microcephaly_df2.loc[microcephaly_df2.gene=="NARS",'gene']= "NARS1"
microcephaly_df2.loc[microcephaly_df2.gene=="SARS",'gene']= "SARS1"
microcephaly_df2.loc[microcephaly_df2.gene=="SPATA5L1",'gene']= "AFG2B"
microcephaly_df2.loc[microcephaly_df2.gene=="C7orf43",'gene']= "TRRAPC14"

In [28]:
#SAVE TO CSV
microcephaly_df2.to_csv("/scratch200/reutj/data/hsg_gene_lists/microcephaly_genes.csv")

In [29]:
#to gmt
output_file="/scratch200/reutj/data/hsg_gene_lists/microcephaly_genes.gmt"
with open(output_file, 'w') as f:
    # Create a line in GMT format for one gene set
    line = f"microcephaly_genes\tDescription\t{'\t'.join(microcephaly_df2.gene.tolist())}\n"
    f.write(line)

In [37]:
#ges_results_micorcephaly
ges_micro=pd.read_csv("/scratch200/reutj/enrichment_results/ges_results/microcephaly_genes/full_results.csv")

In [38]:
ges_micro

,Unnamed: 0,condition,num_genes_in_lead,%genes_in_lead,nes_score,gsea_pval,p-adj
0,0,radialglia,92/244,27.19%,1.323035,0.0392,0.054880
1,1,proliferating,44/245,8.05%,1.475261,0.0004,0.000875
2,2,differentiating,47/215,30.59%,0.397689,1.0000,1.000000
3,3,IPC,97/241,18.76%,2.562827,0.0000,0.000000
4,4,NPCs,83/244,19.97%,1.864792,0.0005,0.000875
5,5,G1,115/245,39.46%,1.344395,0.0221,0.034378
6,6,S,101/245,19.16%,2.401118,0.0000,0.000000
7,7,G2M,45/244,8.21%,2.012296,0.0000,0.000000
8,8,PostM,83/244,19.97%,1.864792,0.0005,0.000875
9,9,Neuron,68/213,41.05%,0.296857,1.0000,1.000000
10,10,Glioblast,115/243,40.84%,0.912798,0.6925,0.881364
11,11,Neuroblast,206/213,89.50%,-1.000000,0.0000,0.000000
12,12,differentiating_non_cycling,52/215,33.12%,0.401614,1.0000,1.000000
13,13,proliferating_non_cycling,182/221,66.71%,-1.000000,0.0000,0.000000

## Intellectual disability genes

In [9]:
#id genes
ID=pd.read_csv("/scratch200/reutj/data/Intellectual_disability.csv")
ID

,Entity Name,Entity type,Gene Symbol,Sources(; separated),Level4,Level3,Level2,Model_Of_Inheritance,Phenotypes,Omim,...,Position GRCh38 Start,Position GRCh38 End,STR Repeated Sequence,STR Normal Repeats,STR Pathogenic Repeats,Region Haploinsufficiency Score,Region Triplosensitivity Score,Region Required Overlap Percentage,Region Variant Type,Region Verbose Name
0,AAAS,gene,AAAS,Expert Review Green;Expert Review Green;BRIDGE...,Intellectual disability,NaN,NaN,"BIALLELIC, autosomal or pseudoautosomal","Achalasia-addisonianism-alacrimia syndrome, OM...",605378,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AARS,gene,AARS,Expert Review Green,Intellectual disability,NaN,NaN,"BIALLELIC, autosomal or pseudoautosomal","Developmental and epileptic encephalopathy 29,...",601065,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AASS,gene,AASS,Expert Review Green,Intellectual disability,NaN,NaN,"BIALLELIC, autosomal or pseudoautosomal","Hyperlysinemia, OMIM:238700;Hyperlysinemia (di...",605113,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ABAT,gene,ABAT,Expert Review Green;BRIDGE study SPEED NEURO T...,Intellectual disability,NaN,NaN,"BIALLELIC, autosomal or pseudoautosomal","GABA-transaminase deficiency, 613163;developme...",137150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ABCA2,gene,ABCA2,Expert Review Green;Literature,Intellectual disability,NaN,NaN,"BIALLELIC, autosomal or pseudoautosomal",Intellectual developmental disorder with poor ...,600047,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2786,ISCA-46304-Gain,region,NaN,ClinGen;Expert Review Green,Intellectual disability,NaN,NaN,"X-LINKED: hemizygous mutation in males, monoal...",NaN,NaN,...,154008529.0,154110279.0,NaN,NaN,NaN,NaN,3.0,60.0,cnv_gain,Xq28 region (includes MECP2) Gain
2787,ISCA-46553-Loss,region,NaN,ClinGen;Expert Review Green,Intellectual disability,NaN,NaN,"MONOALLELIC, autosomal or pseudoautosomal, imp...",NaN,NaN,...,136684193.0,148623326.0,NaN,NaN,NaN,3.0,NaN,60.0,cnv_loss,3q24 Region (includes ZIC1) Loss
2788,ISCA-46742-Loss,region,NaN,ClinGen;Expert Review Green,Intellectual disability,NaN,NaN,"MONOALLELIC, autosomal or pseudoautosomal, imp...",NaN,NaN,...,5497217.0,5760091.0,NaN,NaN,NaN,3.0,NaN,60.0,cnv_loss,7p22.1 region (includes ACTB) Loss
2789,ISCA-46743-Gain,region,NaN,ClinGen;Expert Review Green,Intellectual disability,NaN,NaN,"X-LINKED: hemizygous mutation in males, monoal...",NaN,NaN,...,123900469.0,124102669.0,NaN,NaN,NaN,NaN,3.0,60.0,cnv_gain,Xq25 region (includes STAG2) Gain
2790,ISCA-46743-Loss,region,NaN,ClinGen;Expert Review Green,Intellectual disability,NaN,NaN,"X-LINKED: hemizygous mutation in males, monoal...",NaN,NaN,...,123900469.0,124102669.0,NaN,NaN,NaN,3.0,NaN,60.0,cnv_loss,Xq25 region (includes STAG2) Loss

In [10]:
res=pd.DataFrame(mg.querymany(ID["Gene Symbol"], scopes='symbol', fields='ensembl.gene', species='human'))
res

Input sequence provided is already in string format. No operation performed
Input sequence provided is already in string format. No operation performed
15 input query terms found dup hits:	[('CSTB', 2), ('FMR1', 2), ('GLS', 2), ('ATXN1', 2), ('ATXN10', 2), ('ATXN2', 2), ('ATXN3', 2), ('AT
138 input query terms found no hit:	['AARS', 'APOPT1', 'ARSE', 'C12orf4', 'C12orf65', 'C5orf42', 'CARS', 'CENPJ', 'COL4A3BP', 'CXorf56',

,query,_id,_score,ensembl,notfound
0,AAAS,8086,17.643158,"[{'gene': 'ENSG00000094914'}, {'gene': 'ENSG00...",NaN
1,AARS,NaN,NaN,NaN,True
2,AASS,10157,17.557323,{'gene': 'ENSG00000008311'},NaN
3,ABAT,18,17.612572,{'gene': 'ENSG00000183044'},NaN
4,ABCA2,20,17.672110,{'gene': 'ENSG00000107331'},NaN
...,...,...,...,...,...
2789,nan,NaN,NaN,NaN,True
2790,nan,NaN,NaN,NaN,True
2791,nan,NaN,NaN,NaN,True
2792,nan,NaN,NaN,NaN,True
2793,nan,NaN,NaN,NaN,True

In [26]:
res_short=res.iloc[:2729,:]#get onlythe queries that contain genes

In [31]:
#genes with no hit
for i in res_short.loc[res_short.ensembl.isna(),'query'].tolist():
    print(i)

AARS
APOPT1
ARSE
C12orf4
C12orf65
C5orf42
CARS
CENPJ
COL4A3BP
CXorf56
DARS
FAM126A
H3F3A
H3F3B
HIST1H1E
HIST1H4C
HIST1H4E
IARS
ISPD
KARS
KIAA1109
KIF1BP
LARS
MPP5
MTSS1L
MUT
NARS
QARS
RARS
SARS
SPATA5
SPATA5L1
TAZ
TMEM5
TTC37
VARS
ADPRHL2
ARMC4
C16orf62
C8orf37
FUK
GBA
HARS
HIST1H4I
HIST1H4J
MKL2
YARS
C20orf24
C2orf71
C3orf58
C4orf26
CCDC103
CCDC114
CCDC115
CTGF
DDX58
DSCR3
FAM160B1
FAM58A
HIST1H4B
HIST1H4D
HIST1H4F
HIST3H3
IMPAD1
LRRC6
MT-ATP6
MT-ND1
MT-ND4
MT-TK
MT-TP
SKIV2L
TCP10L2
WDR34
WDR60

In [32]:
#i run them to gprofiler (online) to get these results:
results_g=pd.read_csv("/scratch200/reutj/data/gProfiler_hsapiens_10.3.2025_13-07-45.csv")

In [33]:
results_g

,initial_alias,converted_alias,name,description,namespace
0,AARS,NaN,NaN,NaN,NaN
1,APOPT1,NaN,NaN,NaN,NaN
2,ARSE,NaN,NaN,NaN,NaN
3,C12ORF4,ENSG00000047621,C12orf4,chromosome 12 open reading frame 4 [Source:HGN...,"ENTREZGENE,GENECARDS,HGNC,UNIPROT_GN,WIKIGENE"
4,C12ORF65,NaN,NaN,NaN,NaN
...,...,...,...,...,...
84,SKIV2L,ENSG00000204351,SKIC2,SKI2 subunit of superkiller complex [Source:HG...,UNIPROT_GN
85,TCP10L2,ENSG00000166984,TCP10L2,t-complex 10 like 2 (pseudogene) [Source:HGNC ...,"ENTREZGENE,GENECARDS,HGNC,WIKIGENE"
86,TCP10L2,ENSG00000290751,TCP10L3,t-complex 10 like 3 (pseudogene) [Source:HGNC ...,"ENTREZGENE,GENECARDS,HGNC,WIKIGENE"
87,WDR34,NaN,NaN,NaN,NaN
88,WDR60,NaN,NaN,NaN,NaN

In [35]:
#function to gather the hits for each gene together 
dup_dict={}
for i in range(len(res_short)):
    gene=res['query'][i]
    dup_dict[gene]=[]
for i in range(len(res_short)):
    gene=res['query'][i]
    ens=res.ensembl[i]
    if type(ens)==dict:
        dup_dict[gene].append(ens['gene'])
    elif type(ens)==list:
        dup_dict[gene]=ens

dup_dict

{'AAAS': [{'gene': 'ENSG00000094914'}, {'gene': 'ENSG00000291836'}],
 'AARS': [],
 'AASS': ['ENSG00000008311'],
 'ABAT': ['ENSG00000183044'],
 'ABCA2': ['ENSG00000107331'],
 'ABCC9': ['ENSG00000069431'],
 'ABCD1': ['ENSG00000101986'],
 'ABCD4': ['ENSG00000119688'],
 'ABHD16A': [{'gene': 'ENSG00000224552'},
  {'gene': 'ENSG00000206403'},
  {'gene': 'ENSG00000231488'},
  {'gene': 'ENSG00000204427'},
  {'gene': 'ENSG00000235676'},
  {'gene': 'ENSG00000236063'},
  {'gene': 'ENSG00000230475'}],
 'ABHD5': ['ENSG00000011198'],
 'ACACA': [{'gene': 'ENSG00000278540'}, {'gene': 'ENSG00000275176'}],
 'ACAD9': ['ENSG00000177646'],
 'ACADM': ['ENSG00000117054'],
 'ACADS': ['ENSG00000122971'],
 'ACBD6': ['ENSG00000230124'],
 'ACER3': ['ENSG00000078124'],
 'ACO2': ['ENSG00000100412'],
 'ACOX1': ['ENSG00000161533'],
 'ACSL4': ['ENSG00000068366'],
 'ACTB': ['ENSG00000075624'],
 'ACTG1': [{'gene': 'ENSG00000291420'}, {'gene': 'ENSG00000184009'}],
 'ACTL6A': ['ENSG00000136518'],
 'ACTL6B': ['ENSG00000077080'],
 'ACY1': ['ENSG00000243989'],
 'ADAM22': ['ENSG00000008277'],
 'ADAR': ['ENSG00000160710'],
 'ADARB1': ['ENSG00000197381'],
 'ADAT3': ['ENSG00000213638'],
 'ADD1': ['ENSG00000087274'],
 'ADD3': ['ENSG00000148700'],
 'ADGRG1': ['ENSG00000205336'],
 'ADGRL1': [{'gene': 'ENSG00000288324'}, {'gene': 'ENSG00000072071'}],
 'ADK': ['ENSG00000156110'],
 'ADNP': ['ENSG00000101126'],
 'ADSL': ['ENSG00000239900'],
 'AFF2': ['ENSG00000155966'],
 'AFF3': ['ENSG00000144218'],
 'AFF4': ['ENSG00000072364'],
 'AGA': ['ENSG00000038002'],
 'AGO1': ['ENSG00000092847'],
 'AGO2': ['ENSG00000123908'],
 'AGTPBP1': ['ENSG00000135049'],
 'AHCY': ['ENSG00000101444'],
 'AHDC1': ['ENSG00000126705'],
 'AHI1': ['ENSG00000135541'],
 'AIFM1': ['ENSG00000156709'],
 'AIMP1': ['ENSG00000164022'],
 'AKT3': [{'gene': 'ENSG00000117020'}, {'gene': 'ENSG00000275199'}],
 'ALDH18A1': ['ENSG00000059573'],
 'ALDH3A2': ['ENSG00000072210'],
 'ALDH4A1': ['ENSG00000159423'],
 'ALDH5A1': ['ENSG00000112294'],
 'ALDH7A1': ['ENSG00000164904'],
 'ALG1': ['ENSG00000033011'],
 'ALG11': ['ENSG00000253710'],
 'ALG12': ['ENSG00000182858'],
 'ALG13': ['ENSG00000101901'],
 'ALG3': ['ENSG00000214160'],
 'ALG6': ['ENSG00000088035'],
 'ALG8': ['ENSG00000159063'],
 'ALG9': ['ENSG00000086848'],
 'ALKBH8': ['ENSG00000137760'],
 'ALMS1': ['ENSG00000116127'],
 'AMER1': ['ENSG00000184675'],
 'AMPD2': ['ENSG00000116337'],
 'AMT': ['ENSG00000145020'],
 'ANK2': ['ENSG00000145362'],
 'ANK3': ['ENSG00000151150'],
 'ANKRD11': ['ENSG00000167522'],
 'ANKRD17': ['ENSG00000132466'],
 'ANO4': [{'gene': 'ENSG00000262139'}, {'gene': 'ENSG00000151572'}],
 'AP1G1': ['ENSG00000166747'],
 'AP1S1': ['ENSG00000106367'],
 'AP1S2': ['ENSG00000182287'],
 'AP2M1': ['ENSG00000161203'],
 'AP3B1': ['ENSG00000132842'],
 'AP3B2': ['ENSG00000103723'],
 'AP4B1': ['ENSG00000134262'],
 'AP4E1': ['ENSG00000081014'],
 'AP4M1': ['ENSG00000221838'],
 'AP4S1': ['ENSG00000100478'],
 'APC2': ['ENSG00000115266'],
 'APOPT1': [],
 'ARCN1': ['ENSG00000095139'],
 'ARF1': ['ENSG00000143761'],
 'ARF3': ['ENSG00000134287'],
 'ARFGEF1': ['ENSG00000066777'],
 'ARFGEF2': ['ENSG00000124198'],
 'ARG1': ['ENSG00000118520'],
 'ARHGEF9': ['ENSG00000131089'],
 'ARID1A': ['ENSG00000117713'],
 'ARID1B': ['ENSG00000049618'],
 'ARID2': ['ENSG00000189079'],
 'ARL13B': ['ENSG00000169379'],
 'ARL6': ['ENSG00000113966'],
 'ARMC9': ['ENSG00000135931'],
 'ARSA': ['ENSG00000100299'],
 'ARSB': ['ENSG00000113273'],
 'ARSE': [],
 'ARV1': ['ENSG00000173409'],
 'ARX': ['ENSG00000004848'],
 'ASAH1': ['ENSG00000104763'],
 'ASH1L': ['ENSG00000116539'],
 'ASL': ['ENSG00000126522'],
 'ASNS': ['ENSG00000070669'],
 'ASPA': ['ENSG00000108381'],
 'ASPM': ['ENSG00000066279'],
 'ASS1': ['ENSG00000130707'],
 'ASXL1': ['ENSG00000171456'],
 'ASXL2': ['ENSG00000143970'],
 'ASXL3': ['ENSG00000141431'],
 'ATAD1': ['ENSG00000138138'],
 'ATAD3A': ['ENSG00000197785'],
 'ATG7': ['ENSG00000197548'],
 'ATIC': ['ENSG00000138363'],
 'ATM': ['ENSG00000149311'],
 'ATN1': ['ENSG00000111676'],
 'ATP13A2': ['ENSG00000159363'],
 'ATP1A1': ['ENSG00000163399'],
 'ATP1A2': ['ENSG00000018625'],
 'ATP1A3': ['ENSG00000105409'],
 'ATP2B1': ['ENSG00000070961'],
 'ATP6AP2': ['ENSG00000182220'],
 'ATP6V0A1': ['ENSG00000033627'],
 'ATP6V0A2': ['ENSG00000185344'],
 'ATP6V0C': ['ENSG00000185883'],
 'ATP6V1A': ['ENSG00000114573'],
 'ATP6V1B2': ['ENSG00000147416'],
 'ATP7A': ['ENSG00000165240'],
 'ATP8A2': ['ENSG00000132932'],
 'ATP9A': ['ENSG00000054793'],
 'ATR': ['ENSG00000175054'],
 'ATRX': ['ENSG00000085224'],
 'AUH': ['ENSG00000148090'],
 'AUTS2': ['ENSG00000158321'],
 'B3GALNT2': [{'gene': 'ENSG00000282880'}, {'gene': 'ENSG00000162885'}],
 'B3GLCT': ['ENSG00000187676'],
 'B4GALNT1': ['ENSG00000135454'],
 'B4GALT7': ['ENSG00000027847'],
 'B9D2': ['ENSG00000123810'],
 'BAP1': ['ENSG00000163930'],
 'BAZ2B': ['ENSG00000123636'],
 'BBS1': ['ENSG00000174483'],
 'BBS10': ['ENSG00000179941'],
 'BBS12': ['ENSG00000181004'],
 'BBS2': ['ENSG00000125124'],
 'BBS4': ['ENSG00000140463'],
 'BBS5': ['ENSG00000163093'],
 'BBS7': ['ENSG00000138686'],
 'BBS9': ['ENSG00000122507'],
 'BCAP31': ['ENSG00000185825'],
 'BCAS3': ['ENSG00000141376'],
 'BCKDHA': ['ENSG00000248098'],
 'BCKDHB': ['ENSG00000083123'],
 'BCKDK': ['ENSG00000103507'],
 'BCL11A': ['ENSG00000119866'],
 'BCL11B': ['ENSG00000127152'],
 'BCOR': ['ENSG00000183337'],
 'BCS1L': ['ENSG00000074582'],
 'BICRA': ['ENSG00000063169'],
 'BLM': ['ENSG00000197299'],
 'BLOC1S1': ['ENSG00000135441'],
 'BMP4': ['ENSG00000125378'],
 'BOLA3': ['ENSG00000163170'],
 'BPTF': ['ENSG00000171634'],
 'BRAF': ['ENSG00000157764'],
 'BRAT1': ['ENSG00000106009'],
 'BRD4': ['ENSG00000141867'],
 'BRF1': ['ENSG00000185024'],
 'BRPF1': ['ENSG00000156983'],
 'BRSK2': [{'gene': 'ENSG00000291428'}, {'gene': 'ENSG00000174672'}],
 'BRWD3': ['ENSG00000165288'],
 'BSCL2': ['ENSG00000168000'],
 'BTD': ['ENSG00000169814'],
 'BUB1': ['ENSG00000169679'],
 'BUB1B': ['ENSG00000156970'],
 'C12orf4': [],
 'C12orf57': ['ENSG00000111678'],
 'C12orf65': [],
 'C2CD3': ['ENSG00000168014'],
 'C2orf69': ['ENSG00000178074'],
 'C5orf42': [],
 'CA2': ['ENSG00000104267'],
 'CA8': ['ENSG00000178538'],
 'CACNA1A': ['ENSG00000141837'],
 'CACNA1B': ['ENSG00000148408'],
 'CACNA1C': [{'gene': 'ENSG00000151067'}, {'gene': 'ENSG00000285479'}],
 'CACNA1D': ['ENSG00000157388'],
 'CACNA1E': ['ENSG00000198216'],
 'CACNA1G': ['ENSG00000006283'],
 'CACNA1I': ['ENSG00000100346'],
 'CACNA2D1': ['ENSG00000153956'],
 'CAD': ['ENSG00000084774'],
 'CAMK2A': ['ENSG00000070808'],
 'CAMK2B': ['ENSG00000058404'],
 'CAMK2D': ['ENSG00000145349'],
 'CAMK4': ['ENSG00000152495'],
 'CAMSAP1': ['ENSG00000130559'],
 'CAMTA1': ['ENSG00000171735'],
 'CAPN15': [{'gene': 'ENSG00000103326'}, {'gene': 'ENSG00000282214'}],
 'CAPRIN1': ['ENSG00000135387'],
 'CARS': [],
 'CASK': ['ENSG00000147044'],
 'CASP2': ['ENSG00000106144'],
 'CBL': ['ENSG00000110395'],
 'CBS': ['ENSG00000160200'],
 'CC2D1A': [{'gene': 'ENSG00000132024'}, {'gene': 'ENSG00000288293'}],
 'CC2D2A': ['ENSG00000048342'],
 'CCBE1': ['ENSG00000183287'],
 'CCDC22': ['ENSG00000101997'],
 'CCDC32': ['ENSG00000128891'],
 'CCDC47': ['ENSG00000108588'],
 'CCDC82': ['ENSG00000149231'],
 'CCDC88C': ['ENSG00000015133'],
 'CCND2': ['ENSG00000118971'],
 'CDC42': ['ENSG00000070831'],
 'CDC6': ['ENSG00000094804'],
 'CDH11': ['ENSG00000140937'],
 'CDH2': ['ENSG00000170558'],
 'CDK10': ['ENSG00000185324'],
 'CDK13': ['ENSG00000065883'],
 'CDK16': ['ENSG00000102225'],
 'CDK19': ['ENSG00000155111'],
 'CDK5RAP2': ['ENSG00000136861'],
 'CDK8': ['ENSG00000132964'],
 'CDKL5': ['ENSG00000008086'],
 'CDON': ['ENSG00000064309'],
 'CELF2': ['ENSG00000048740'],
 'CENPF': ['ENSG00000117724'],
 'CENPJ': [],
 'CEP104': ['ENSG00000116198'],
 'CEP120': ['ENSG00000168944'],
 'CEP135': ['ENSG00000174799'],
 'CEP152': ['ENSG00000103995'],
 'CEP290': ['ENSG00000198707'],
 'CEP41': ['ENSG00000106477'],
 'CEP55': ['ENSG00000138180'],
 'CEP57': ['ENSG00000166037'],
 'CEP83': ['ENSG00000173588'],
 'CEP85L': ['ENSG00000111860'],
 'CHAMP1': ['ENSG00000198824'],
 'CHD2': ['ENSG00000173575'],
 'CHD3': ['ENSG00000170004'],
 'CHD4': ['ENSG00000111642'],
 'CHD5': ['ENSG00000116254'],
 'CHD7': ['ENSG00000171316'],
 'CHD8': ['ENSG00000100888'],
 'CHKA': ['ENSG00000110721'],
 'CHKB': ['ENSG00000100288'],
 'CHMP1A': ['ENSG00000131165'],
 'CIC': ['ENSG00000079432'],
 'CIT': ['ENSG00000122966'],
 'CKAP2L': ['ENSG00000169607'],
 'CLCN3': ['ENSG00000109572'],
 'CLCN4': ['ENSG00000073464'],
 'CLCN6': ['ENSG00000011021'],
 'CLDN11': ['ENSG00000013297'],
 'CLDN5': ['ENSG00000184113'],
 'CLEC16A': ['ENSG00000038532'],
 'CLN3': [{'gene': 'ENSG00000261832'}, {'gene': 'ENSG00000188603'}],
 'CLN5': ['ENSG00000102805'],
 'CLN6': ['ENSG00000128973'],
 'CLN8': [{'gene': 'ENSG00000278220'}, {'gene': 'ENSG00000182372'}],
 'CLP1': ['ENSG00000172409'],
 'CLPB': ['ENSG00000162129'],
 'CLTC': ['ENSG00000141367'],
 'CNKSR2': ['ENSG00000149970'],
 'CNNM2': ['ENSG00000148842'],
 'CNOT1': ['ENSG00000125107'],
 'CNOT2': ['ENSG00000111596'],
 'CNOT3': [{'gene': 'ENSG00000275979'},
  {'gene': 'ENSG00000277114'},
  {'gene': 'ENSG00000277600'},
  {'gene': 'ENSG00000274616'},
  {'gene': 'ENSG00000277615'},
  {'gene': 'ENSG00000088038'},
  {'gene': 'ENSG00000274176'},
  {'gene': 'ENSG00000274941'},
  {'gene': 'ENSG00000273943'},
  {'gene': 'ENSG00000276082'}],
 'CNOT9': ['ENSG00000144580'],
 'CNTNAP1': ['ENSG00000108797'],
 'CNTNAP2': [{'gene': 'ENSG00000278728'}, {'gene': 'ENSG00000174469'}],
 'COASY': ['ENSG00000068120'],
 'COG1': ['ENSG00000166685'],
 'COG4': ['ENSG00000103051'],
 'COG5': [{'gene': 'ENSG00000164597'}, {'gene': 'ENSG00000284369'}],
 'COG6': ['ENSG00000133103'],
 'COG7': ['ENSG00000168434'],
 'COG8': ['ENSG00000213380'],
 'COL4A1': ['ENSG00000187498'],
 'COL4A2': ['ENSG00000134871'],
 'COL4A3BP': [],
 'COLEC11': ['ENSG00000118004'],
 'COPB2': ['ENSG00000184432'],
 'COQ4': ['ENSG00000167113'],
 'COQ8A': ['ENSG00000163050'],
 'COX10': ['ENSG00000006695'],
 'COX11': ['ENSG00000166260'],
 'COX15': ['ENSG00000014919'],
 'CPE': ['ENSG00000109472'],
 'CPLX1': ['ENSG00000168993'],
 'CPS1': ['ENSG00000021826'],
 'CRADD': ['ENSG00000169372'],
 'CRB2': ['ENSG00000148204'],
 'CREBBP': ['ENSG00000005339'],
 'CSDE1': ['ENSG00000009307'],
 'CSNK1G1': ['ENSG00000169118'],
 'CSNK2A1': ['ENSG00000101266'],
 'CSNK2B': [{'gene': 'ENSG00000224774'},
  {'gene': 'ENSG00000232960'},
  {'gene': 'ENSG00000228875'},
  {'gene': 'ENSG00000206406'},
  {'gene': 'ENSG00000224398'},
  {'gene': 'ENSG00000204435'},
  {'gene': 'ENSG00000230700'}],
 'CSPP1': ['ENSG00000104218'],
 'CSTB': ['ENSG00000160213', 'ENSG00000160213'],
 'CTBP1': ['ENSG00000159692'],
 'CTCF': ['ENSG00000102974'],
 'CTDP1': [{'gene': 'ENSG00000282752'}, {'gene': 'ENSG00000060069'}],
 'CTNNA2': ['ENSG00000066032'],
 'CTNNB1': ['ENSG00000168036'],
 'CTNND1': ['ENSG00000198561'],
 'CTR9': ['ENSG00000198730'],
 'CTSA': ['ENSG00000064601'],
 'CTSD': ['ENSG00000117984'],
 'CTU2': ['ENSG00000174177'],
 'CUL3': ['ENSG00000036257'],
 'CUL4B': ['ENSG00000158290'],
 'CUX1': ['ENSG00000257923'],
 'CUX2': ['ENSG00000111249'],
 'CWC27': ['ENSG00000153015'],
 'CWF19L1': ['ENSG00000095485'],
 'CXorf56': [],
 'CYB5R3': ['ENSG00000100243'],
 'CYC1': ['ENSG00000179091'],
 'CYFIP2': ['ENSG00000055163'],
 'D2HGDH': ['ENSG00000180902'],
 'DAG1': ['ENSG00000173402'],
 'DAGLA': ['ENSG00000134780'],
 'DARS': [],
 'DARS2': ['ENSG00000117593'],
 'DBT': ['ENSG00000137992'],
 'DCAF17': ['ENSG00000115827'],
 'DCHS1': ['ENSG00000166341'],
 'DCPS': ['ENSG00000110063'],
 'DCX': ['ENSG00000077279'],
 'DDB1': ['ENSG00000167986'],
 'DDC': ['ENSG00000132437'],
 'DDHD2': ['ENSG00000085788'],
 'DDX11': ['ENSG00000013573'],
 'DDX23': ['ENSG00000174243'],
 'DDX3X': ['ENSG00000215301'],
 'DDX59': ['ENSG00000118197'],
 'DDX6': ['ENSG00000110367'],
 'DEAF1': [{'gene': 'ENSG00000282712'}, {'gene': 'ENSG00000177030'}],
 'DEGS1': ['ENSG00000143753'],
 'DENND5B': ['ENSG00000170456'],
 'DEPDC5': ['ENSG00000100150'],
 'DHCR24': ['ENSG00000116133'],
 'DHCR7': ['ENSG00000172893'],
 'DHDDS': ['ENSG00000117682'],
 'DHFR': ['ENSG00000228716'],
 'DHPS': ['ENSG00000095059'],
 'DHTKD1': ['ENSG00000181192'],
 'DHX30': ['ENSG00000132153'],
 'DHX37': ['ENSG00000150990'],
 'DHX9': ['ENSG00000135829'],
 'DIAPH1': ['ENSG00000131504'],
 'DIS3L2': ['ENSG00000144535'],
 'DKC1': ['ENSG00000130826'],
 'DLD': ['ENSG00000091140'],
 'DLG3': ['ENSG00000082458'],
 'DLG4': ['ENSG00000132535'],
 'DLL1': [{'gene': 'ENSG00000275555'}, {'gene': 'ENSG00000198719'}],
 'DMD': ['ENSG00000198947'],
 'DMXL2': ['ENSG00000104093'],
 'DNAJC12': ['ENSG00000108176'],
 'DNAJC19': ['ENSG00000205981'],
 'DNM1': ['ENSG00000106976'],
 'DNM1L': ['ENSG00000087470'],
 'DNMT3A': ['ENSG00000119772'],
 'DNMT3B': ['ENSG00000088305'],
 'DOCK3': ['ENSG00000088538'],
 'DOCK4': ['ENSG00000128512'],
 'DOCK6': ['ENSG00000130158'],
 'DOCK7': ['ENSG00000116641'],
 'DOHH': ['ENSG00000129932'],
 'DOLK': ['ENSG00000175283'],
 'DPAGT1': ['ENSG00000172269'],
 'DPF2': ['ENSG00000133884'],
 'DPH1': ['ENSG00000108963'],
 'DPH5': ['ENSG00000117543'],
 'DPM1': ['ENSG00000000419'],
 'DPM2': ['ENSG00000136908'],
 'DPYD': ['ENSG00000188641'],
 'DPYS': ['ENSG00000147647'],
 'DPYSL5': ['ENSG00000157851'],
 'DTYMK': ['ENSG00000168393'],
 'DYM': ['ENSG00000141627'],
 'DYNC1H1': ['ENSG00000197102'],
 'DYRK1A': ['ENSG00000157540'],
 'EARS2': ['ENSG00000103356'],
 'EBF3': ['ENSG00000108001'],
 'EBP': ['ENSG00000147155'],
 'EDEM3': ['ENSG00000116406'],
 'EED': ['ENSG00000074266'],
 'EEF1A2': ['ENSG00000101210'],
 'EFTUD2': ['ENSG00000108883'],
 'EHMT1': ['ENSG00000181090'],
 'EIF2AK2': ['ENSG00000055332'],
 'EIF2AK3': ['ENSG00000172071'],
 'EIF2S3': ['ENSG00000130741'],
 'EIF3F': ['ENSG00000175390'],
 'EIF4A2': ['ENSG00000156976'],
 'EIF4A3': [{'gene': 'ENSG00000141543'}, {'gene': 'ENSG00000291508'}],
 'EIF5A': [{'gene': 'ENSG00000132507'}, {'gene': 'ENSG00000288145'}],
 'ELAC2': ['ENSG00000006744'],
 'ELOVL4': ['ENSG00000118402'],
 'ELP2': ['ENSG00000134759'],
 'EMC1': ['ENSG00000127463'],
 'EMC10': ['ENSG00000161671'],
 'EML1': ['ENSG00000066629'],
 'EMX2': ['ENSG00000170370'],
 'ENTPD1': ['ENSG00000138185'],
 'EP300': ['ENSG00000100393'],
 'EPG5': ['ENSG00000152223'],
 'ERBB4': ['ENSG00000178568'],
 'ERCC1': ['ENSG00000012061'],
 'ERCC2': ['ENSG00000104884'],
 'ERCC3': ['ENSG00000163161'],
 'ERCC5': ['ENSG00000134899'],
 'ERCC6': ['ENSG00000225830'],
 'ERCC6L2': ['ENSG00000182150'],
 'ERCC8': ['ENSG00000049167'],
 'ERI1': [{'gene': 'ENSG00000292301'}, {'gene': 'ENSG00000104626'}],
 'ERLIN2': ['ENSG00000147475'],
 'ESAM': ['ENSG00000149564'],
 'ESCO2': ['ENSG00000171320'],
 'ETFA': ['ENSG00000140374'],
 'ETFB': ['ENSG00000105379'],
 'ETFDH': ['ENSG00000171503'],
 'ETHE1': ['ENSG00000105755'],
 'EXOSC3': ['ENSG00000107371'],
 'EXT2': ['ENSG00000151348'],
 'EXTL3': ['ENSG00000012232'],
 'EZH1': ['ENSG00000108799'],
 'EZH2': ['ENSG00000106462'],
 'FAM126A': [],
 'FAM177A1': ['ENSG00000151327'],
 'FAM20C': [{'gene': 'ENSG00000177706'},
  {'gene': 'ENSG00000282147'},
  {'gene': 'ENSG00000288499'},
  {'gene': 'ENSG00000281429'}],
 'FAM50A': ['ENSG00000071859'],
 'FAR1': ['ENSG00000197601'],
 'FARS2': ['ENSG00000145982'],
 'FARSA': ['ENSG00000179115'],
 'FAT4': ['ENSG00000196159'],
 'FBRSL1': ['ENSG00000112787'],
 'FBXL3': ['ENSG00000005812'],
 'FBXL4': ['ENSG00000112234'],
 'FBXO11': ['ENSG00000138081'],
 'FBXO28': ['ENSG00000143756'],
 'FBXO31': ['ENSG00000103264'],
 'FBXW11': ['ENSG00000072803'],
 'FBXW7': ['ENSG00000109670'],
 'FEM1B': ['ENSG00000169018'],
 'FGD1': ['ENSG00000102302'],
 'FGF12': ['ENSG00000114279'],
 'FH': ['ENSG00000091483'],
 'FIG4': ['ENSG00000112367'],
 'FILIP1': ['ENSG00000118407'],
 'FKRP': ['ENSG00000181027'],
 'FKTN': ['ENSG00000106692'],
 'FLVCR2': ['ENSG00000119686'],
 'FMN2': ['ENSG00000155816'],
 'FMR1': ['ENSG00000102081', 'ENSG00000102081'],
 'FOLR1': ['ENSG00000110195'],
 'FOXG1': ['ENSG00000176165'],
 'FOXP1': ['ENSG00000114861'],
 'FOXP2': ['ENSG00000128573'],
 'FOXRED1': ['ENSG00000110074'],
 'FRMD5': ['ENSG00000171877'],
 'FRMPD4': ['ENSG00000169933'],
 'FTCD': [{'gene': 'ENSG00000281775'}, {'gene': 'ENSG00000160282'}],
 'FTSJ1': ['ENSG00000068438'],
 'FUCA1': ['ENSG00000179163'],
 'FUT8': ['ENSG00000033170'],
 'GABBR2': ['ENSG00000136928'],
 'GABRA1': ['ENSG00000022355'],
 'GABRA2': ['ENSG00000151834'],
 'GABRA5': ['ENSG00000186297'],
 'GABRB2': ['ENSG00000145864'],
 'GABRB3': ['ENSG00000166206'],
 'GABRD': ['ENSG00000187730'],
 'GABRG2': ['ENSG00000113327'],
 'GAD1': ['ENSG00000128683'],
 'GALC': ['ENSG00000054983'],
 'GALE': ['ENSG00000117308'],
 'GALNT2': ['ENSG00000143641'],
 'GALT': ['ENSG00000213930'],
 'GAMT': ['ENSG00000130005'],
 'GAN': ['ENSG00000261609'],
 'GATAD2B': [{'gene': 'ENSG00000261992'}, {'gene': 'ENSG00000143614'}],
 'GATM': ['ENSG00000171766'],
 'GCDH': ['ENSG00000105607'],
 'GCH1': ['ENSG00000131979'],
 'GCSH': [{'gene': 'ENSG00000140905'}, {'gene': 'ENSG00000291958'}],
 'GDI1': ['ENSG00000203879'],
 'GEMIN5': ['ENSG00000082516'],
 'GFAP': ['ENSG00000131095'],
 'GFER': [{'gene': 'ENSG00000291944'}, {'gene': 'ENSG00000127554'}],
 'GFM1': ['ENSG00000168827'],
 'GJC2': ['ENSG00000198835'],
 'GK': ['ENSG00000198814'],
 'GLB1': ['ENSG00000170266'],
 'GLDC': ['ENSG00000178445'],
 'GLI2': ['ENSG00000074047'],
 'GLIS3': ['ENSG00000107249'],
 'GLRA2': ['ENSG00000101958'],
 'GLUL': ['ENSG00000135821'],
 'GLYCTK': ['ENSG00000168237'],
 'GM2A': ['ENSG00000196743'],
 'GMPPA': ['ENSG00000144591'],
 'GMPPB': ['ENSG00000173540'],
 'GNAI1': ['ENSG00000127955'],
 'GNAO1': ['ENSG00000087258'],
 'GNAS': ['ENSG00000087460'],
 'GNB1': ['ENSG00000078369'],
 'GNB2': ['ENSG00000172354'],
 'GNB5': ['ENSG00000069966'],
 'GNPAT': ['ENSG00000116906'],
 'GNPTAB': ['ENSG00000111670'],
 'GNPTG': ['ENSG00000090581'],
 'GNS': ['ENSG00000135677'],
 'GPAA1': ['ENSG00000197858'],
 'GPC3': ['ENSG00000147257'],
 'GPC4': ['ENSG00000076716'],
 'GPT2': ['ENSG00000166123'],
 'GRIA1': ['ENSG00000155511'],
 'GRIA2': ['ENSG00000120251'],
 'GRIA3': ['ENSG00000125675'],
 'GRIA4': ['ENSG00000152578'],
 'GRID2': ['ENSG00000152208'],
 'GRIK2': ['ENSG00000164418'],
 'GRIN1': ['ENSG00000176884'],
 'GRIN2A': ['ENSG00000183454'],
 'GRIN2B': ['ENSG00000273079'],
 'GRIN2D': ['ENSG00000105464'],
 'GRM1': ['ENSG00000152822'],
 'GRM7': ['ENSG00000196277'],
 'GTF2E2': ['ENSG00000197265'],
 'GTF2H5': ['ENSG00000272047'],
 'GTF3C5': ['ENSG00000148308'],
 'GTPBP2': ['ENSG00000172432'],
 'GTPBP3': ['ENSG00000130299'],
 'GUSB': ['ENSG00000169919'],
 'H3F3A': [],
 'H3F3B': [],
 'HACE1': ['ENSG00000085382'],
 'HADHA': ['ENSG00000084754'],
 'HCCS': ['ENSG00000004961'],
 'HCFC1': ['ENSG00000172534'],
 'HCN1': ['ENSG00000164588'],
 'HDAC4': ['ENSG00000068024'],
 'HDAC8': ['ENSG00000147099'],
 'HECTD4': ['ENSG00000173064'],
 'HECW2': ['ENSG00000138411'],
 'HEPACAM': ['ENSG00000165478'],
 'HERC1': ['ENSG00000103657'],
 'HERC2': [{'gene': 'ENSG00000277278'},
  {'gene': 'ENSG00000128731'},
  {'gene': 'ENSG00000276802'}],
 'HESX1': ['ENSG00000163666'],
 'HEXA': ['ENSG00000213614'],
 'HEXB': ['ENSG00000049860'],
 'HGSNAT': ['ENSG00000165102'],
 'HIBCH': ['ENSG00000198130'],
 'HID1': ['ENSG00000167861'],
 'HIST1H1E': [],
 'HIST1H4C': [],
 'HIST1H4E': [],
 'HIVEP2': ['ENSG00000010818'],
 'HK1': ['ENSG00000156515'],
 'HLCS': ['ENSG00000159267'],
 'HMGB1': ['ENSG00000189403'],
 'HMGCL': ['ENSG00000117305'],
 'HNMT': ['ENSG00000150540'],
 'HNRNPH1': [{'gene': 'ENSG00000284254'}, {'gene': 'ENSG00000169045'}],
 'HNRNPH2': ['ENSG00000126945'],
 'HNRNPK': ['ENSG00000165119'],
 'HNRNPR': [{'gene': 'ENSG00000282958'}, {'gene': 'ENSG00000125944'}],
 'HNRNPU': ['ENSG00000153187'],
 'HOXA1': ['ENSG00000105991'],
 'HPD': ['ENSG00000158104'],
 'HPDL': ['ENSG00000186603'],
 'HPRT1': ['ENSG00000165704'],
 'HRAS': [{'gene': 'ENSG00000276536'}, {'gene': 'ENSG00000174775'}],
 'HSD17B10': ['ENSG00000072506'],
 'HSD17B4': ['ENSG00000133835'],
 'HSPD1': ['ENSG00000144381'],
 'HTRA2': ['ENSG00000115317'],
 'HUWE1': ['ENSG00000086758'],
 'IARS': [],
 'IBA57': ['ENSG00000181873'],
 'IDH2': ['ENSG00000182054'],
 'IDS': ['ENSG00000010404'],
 'IDUA': ['ENSG00000127415'],

In [74]:
no_hit=[]
gprof_genes=results_g.initial_alias.tolist()
for i in gprof_genes:
    ens=results_g.loc[results_g.initial_alias==i,'converted_alias']
    if len(ens)==1:
        if not ens.isna().item():
            print(i,ens.item())
            dup_dict[i]=[ens.item()]
        else:
            print("no hit: ",i)
            no_hit.append(i)
    elif len(ens)>1:
        print("more than one hit: ",i)

no hit:  AARS
no hit:  APOPT1
no hit:  ARSE
C12ORF4 ENSG00000047621
no hit:  C12ORF65
no hit:  C5ORF42
CARS ENSG00000110619
CENPJ ENSG00000151849
COL4A3BP ENSG00000113163
no hit:  CXORF56
no hit:  DARS
no hit:  FAM126A
more than one hit:  H3F3A
more than one hit:  H3F3A
no hit:  H3F3B
HIST1H1E ENSG00000168298
no hit:  HIST1H4C
no hit:  HIST1H4E
no hit:  IARS
no hit:  ISPD
no hit:  KARS
no hit:  KIAA1109
no hit:  KIF1BP
no hit:  LARS
no hit:  MPP5
no hit:  MTSS1L
MUT ENSG00000146085
no hit:  NARS
no hit:  QARS
no hit:  RARS
no hit:  SARS
no hit:  SPATA5
no hit:  SPATA5L1
TAZ ENSG00000102125
no hit:  TMEM5
no hit:  TTC37
VARS ENSG00000204394
no hit:  ADPRHL2
no hit:  ARMC4
no hit:  C16ORF62
no hit:  C8ORF37
no hit:  FUK
GBA ENSG00000177628
no hit:  HARS
no hit:  HIST1H4I
more than one hit:  HIST1H4J
more than one hit:  HIST1H4J
more than one hit:  HIST1H4J
more than one hit:  HIST1H4J
more than one hit:  HIST1H4J
more than one hit:  HIST1H4J
more than one hit:  HIST1H4J
more than one hit:  HIST1H4J
more than one hit:  HIST1H4J
more than one hit:  HIST1H4J
more than one hit:  HIST1H4J
more than one hit:  HIST1H4J
more than one hit:  HIST1H4J
more than one hit:  HIST1H4J
no hit:  MKL2
YARS ENSG00000134684
no hit:  C20ORF24
no hit:  C2ORF71
no hit:  C3ORF58
no hit:  C4ORF26
CCDC103 ENSG00000167131
no hit:  CCDC114
CCDC115 ENSG00000136710
no hit:  CTGF
no hit:  DDX58
no hit:  DSCR3
no hit:  FAM160B1
no hit:  FAM58A
no hit:  HIST1H4B
no hit:  HIST1H4D
no hit:  HIST1H4F
no hit:  HIST3H3
IMPAD1 ENSG00000104331
no hit:  LRRC6
MT-ATP6 ENSG00000198899
MT-ND1 ENSG00000198888
MT-ND4 ENSG00000198886
MT-TK ENSG00000210156
MT-TP ENSG00000210196
SKIV2L ENSG00000204351
more than one hit:  TCP10L2
more than one hit:  TCP10L2
no hit:  WDR34
no hit:  WDR60

In [85]:
#more than one hit genes in this list
dup_dict['H3F3A']='ENSG00000163041'
dup_dict['HIST1H4J']='ENSG00000296368'
dup_dict['TCP10L2']='ENSG00000166984'

In [81]:
#duplist more than one hit
double_hit=[]
for k,v in dup_dict.items():
    if len(v)>1:
        print(k,":",v)
        double_hit.append(k)
#0,3,0,1,1,0,1,1,1,0,0

AAAS : [{'gene': 'ENSG00000094914'}, {'gene': 'ENSG00000291836'}]
ABHD16A : [{'gene': 'ENSG00000224552'}, {'gene': 'ENSG00000206403'}, {'gene': 'ENSG00000231488'}, {'gene': 'ENSG00000204427'}, {'gene': 'ENSG00000235676'}, {'gene': 'ENSG00000236063'}, {'gene': 'ENSG00000230475'}]
ACACA : [{'gene': 'ENSG00000278540'}, {'gene': 'ENSG00000275176'}]
ACTG1 : [{'gene': 'ENSG00000291420'}, {'gene': 'ENSG00000184009'}]
ADGRL1 : [{'gene': 'ENSG00000288324'}, {'gene': 'ENSG00000072071'}]
AKT3 : [{'gene': 'ENSG00000117020'}, {'gene': 'ENSG00000275199'}]
ANO4 : [{'gene': 'ENSG00000262139'}, {'gene': 'ENSG00000151572'}]
B3GALNT2 : [{'gene': 'ENSG00000282880'}, {'gene': 'ENSG00000162885'}]
BRSK2 : [{'gene': 'ENSG00000291428'}, {'gene': 'ENSG00000174672'}]
CACNA1C : [{'gene': 'ENSG00000151067'}, {'gene': 'ENSG00000285479'}]
CAPN15 : [{'gene': 'ENSG00000103326'}, {'gene': 'ENSG00000282214'}]
CC2D1A : [{'gene': 'ENSG00000132024'}, {'gene': 'ENSG00000288293'}]
CLN3 : [{'gene': 'ENSG00000261832'}, {'gene': 'ENSG00000188603'}]
CLN8 : [{'gene': 'ENSG00000278220'}, {'gene': 'ENSG00000182372'}]
CNOT3 : [{'gene': 'ENSG00000275979'}, {'gene': 'ENSG00000277114'}, {'gene': 'ENSG00000277600'}, {'gene': 'ENSG00000274616'}, {'gene': 'ENSG00000277615'}, {'gene': 'ENSG00000088038'}, {'gene': 'ENSG00000274176'}, {'gene': 'ENSG00000274941'}, {'gene': 'ENSG00000273943'}, {'gene': 'ENSG00000276082'}]
CNTNAP2 : [{'gene': 'ENSG00000278728'}, {'gene': 'ENSG00000174469'}]
COG5 : [{'gene': 'ENSG00000164597'}, {'gene': 'ENSG00000284369'}]
CSNK2B : [{'gene': 'ENSG00000224774'}, {'gene': 'ENSG00000232960'}, {'gene': 'ENSG00000228875'}, {'gene': 'ENSG00000206406'}, {'gene': 'ENSG00000224398'}, {'gene': 'ENSG00000204435'}, {'gene': 'ENSG00000230700'}]
CSTB : ['ENSG00000160213', 'ENSG00000160213']
CTDP1 : [{'gene': 'ENSG00000282752'}, {'gene': 'ENSG00000060069'}]
DEAF1 : [{'gene': 'ENSG00000282712'}, {'gene': 'ENSG00000177030'}]
DLL1 : [{'gene': 'ENSG00000275555'}, {'gene': 'ENSG00000198719'}]
EIF4A3 : [{'gene': 'ENSG00000141543'}, {'gene': 'ENSG00000291508'}]
EIF5A : [{'gene': 'ENSG00000132507'}, {'gene': 'ENSG00000288145'}]
ERI1 : [{'gene': 'ENSG00000292301'}, {'gene': 'ENSG00000104626'}]
FAM20C : [{'gene': 'ENSG00000177706'}, {'gene': 'ENSG00000282147'}, {'gene': 'ENSG00000288499'}, {'gene': 'ENSG00000281429'}]
FMR1 : ['ENSG00000102081', 'ENSG00000102081']
FTCD : [{'gene': 'ENSG00000281775'}, {'gene': 'ENSG00000160282'}]
GATAD2B : [{'gene': 'ENSG00000261992'}, {'gene': 'ENSG00000143614'}]
GCSH : [{'gene': 'ENSG00000140905'}, {'gene': 'ENSG00000291958'}]
GFER : [{'gene': 'ENSG00000291944'}, {'gene': 'ENSG00000127554'}]
HERC2 : [{'gene': 'ENSG00000277278'}, {'gene': 'ENSG00000128731'}, {'gene': 'ENSG00000276802'}]
HNRNPH1 : [{'gene': 'ENSG00000284254'}, {'gene': 'ENSG00000169045'}]
HNRNPR : [{'gene': 'ENSG00000282958'}, {'gene': 'ENSG00000125944'}]
HRAS : [{'gene': 'ENSG00000276536'}, {'gene': 'ENSG00000174775'}]
KANSL1 : [{'gene': 'ENSG00000120071'}, {'gene': 'ENSG00000278458'}, {'gene': 'ENSG00000275867'}]
KAT6B : [{'gene': 'ENSG00000281813'}, {'gene': 'ENSG00000156650'}]
KCNQ2 : [{'gene': 'ENSG00000075043'}, {'gene': 'ENSG00000281151'}]
KCNT2 : [{'gene': 'ENSG00000162687'}, {'gene': 'ENSG00000291999'}]
KIF5C : [{'gene': 'ENSG00000276734'}, {'gene': 'ENSG00000168280'}]
LSS : [{'gene': 'ENSG00000281289'}, {'gene': 'ENSG00000160285'}]
MAGEL2 : [{'gene': 'ENSG00000254585'}, {'gene': 'ENSG00000288188'}]
MASP1 : [{'gene': 'ENSG00000291559'}, {'gene': 'ENSG00000127241'}]
MBOAT7 : [{'gene': 'ENSG00000273592'}, {'gene': 'ENSG00000277923'}, {'gene': 'ENSG00000276935'}, {'gene': 'ENSG00000125505'}, {'gene': 'ENSG00000277733'}, {'gene': 'ENSG00000277025'}, {'gene': 'ENSG00000278322'}, {'gene': 'ENSG00000275118'}, {'gene': 'ENSG00000274194'}, {'gene': 'ENSG00000278519'}]
MCCC2 : [{'gene': 'ENSG00000281742'}, {'gene': 'ENSG00000131844'}, {'gene': 'ENSG00000275300'}]
NDE1 : [{'gene': 'ENSG00000072864'}, {'gene': 'ENSG00000275911'}]
NDUFS1 : [{'gene': 'ENSG00000283447'}, {'gene': 'ENSG00000023228'}]
NEU1 : [{'gene': 'ENSG00000204386'}, {'gene': 'ENSG00000227129'}, {'gene': 'ENSG00000227315'}, {'gene': 'ENSG00000184494'}, {'gene': 'ENSG00000234846'}, {'gene': 'ENSG00000228691'}, {'gene': 'ENSG00000223957'}, {'gene': 'ENSG00000234343'}]
NSDHL : [{'gene': 'ENSG00000147383'}, {'gene': 'ENSG00000292192'}]
OCLN : [{'gene': 'ENSG00000197822'}, {'gene': 'ENSG00000273814'}]
OSGEP : [{'gene': 'ENSG00000291794'}, {'gene': 'ENSG00000092094'}]
OTUD5 : [{'gene': 'ENSG00000292211'}, {'gene': 'ENSG00000068308'}]
PARN : [{'gene': 'ENSG00000140694'}, {'gene': 'ENSG00000274829'}]
PCGF2 : [{'gene': 'ENSG00000277258'}, {'gene': 'ENSG00000278644'}]
PEX5 : [{'gene': 'ENSG00000288217'}, {'gene': 'ENSG00000139197'}]
PIGW : [{'gene': 'ENSG00000277161'}, {'gene': 'ENSG00000275600'}]
POLR2A : [{'gene': 'ENSG00000284832'}, {'gene': 'ENSG00000181222'}]
PQBP1 : [{'gene': 'ENSG00000102103'}, {'gene': 'ENSG00000292208'}]
PRPF8 : [{'gene': 'ENSG00000174231'}, {'gene': 'ENSG00000274442'}]
PTEN : [{'gene': 'ENSG00000171862'}, {'gene': 'ENSG00000284792'}]
SARS2 : [{'gene': 'ENSG00000104835'}, {'gene': 'ENSG00000283104'}]
SDCCAG8 : [{'gene': 'ENSG00000054282'}, {'gene': 'ENSG00000276111'}]
SHANK3 : [{'gene': 'ENSG00000292254'}, {'gene': 'ENSG00000251322'}]
SLC25A12 : [{'gene': 'ENSG00000292099'}, {'gene': 'ENSG00000115840'}]
SLC35A2 : [{'gene': 'ENSG00000292209'}, {'gene': 'ENSG00000102100'}]
SLC6A3 : [{'gene': 'ENSG00000142319'}, {'gene': 'ENSG00000276996'}]
SMARCB1 : [{'gene': 'ENSG00000099956'}, {'gene': 'ENSG00000275837'}]
SMPD4 : [{'gene': 'ENSG00000136699'}, {'gene': 'ENSG00000292130'}]
STRA6 : [{'gene': 'ENSG00000137868'}, {'gene': 'ENSG00000288257'}]
SURF1 : [{'gene': 'ENSG00000280627'}, {'gene': 'ENSG00000148290'}]
SYNCRIP : [{'gene': 'ENSG00000271793'}, {'gene': 'ENSG00000135316'}]
SYNGAP1 : [{'gene': 'ENSG00000227460'}, {'gene': 'ENSG00000197283'}]
TAF4 : [{'gene': 'ENSG00000130699'}, {'gene': 'ENSG00000280529'}]
TBCD : [{'gene': 'ENSG00000141556'}, {'gene': 'ENSG00000278759'}]
TCF20 : [{'gene': 'ENSG00000276461'}, {'gene': 'ENSG00000100207'}, {'gene': 'ENSG00000262024'}]
TFE3 : [{'gene': 'ENSG00000068323'}, {'gene': 'ENSG00000292217'}]
TRAPPC12 : [{'gene': 'ENSG00000274891'}, {'gene': 'ENSG00000171853'}]
TRAPPC4 : [{'gene': 'ENSG00000280495'}, {'gene': 'ENSG00000196655'}]
TSEN34 : [{'gene': 'ENSG00000274129'}, {'gene': 'ENSG00000274078'}, {'gene': 'ENSG00000274672'}, {'gene': 'ENSG00000278605'}, {'gene': 'ENSG00000273896'}, {'gene': 'ENSG00000275165'}, {'gene': 'ENSG00000170892'}, {'gene': 'ENSG00000278712'}, {'gene': 'ENSG00000274796'}, {'gene': 'ENSG00000278622'}]
TTC5 : [{'gene': 'ENSG00000136319'}, {'gene': 'ENSG00000291781'}]
TUBB : [{'gene': 'ENSG00000235067'}, {'gene': 'ENSG00000183311'}, {'gene': 'ENSG00000232575'}, {'gene': 'ENSG00000196230'}, {'gene': 'ENSG00000232421'}, {'gene': 'ENSG00000224156'}, {'gene': 'ENSG00000227739'}, {'gene': 'ENSG00000229684'}]
UBR7 : [{'gene': 'ENSG00000278787'}, {'gene': 'ENSG00000012963'}]
VARS2 : [{'gene': 'ENSG00000234032'}, {'gene': 'ENSG00000230985'}, {'gene': 'ENSG00000223494'}, {'gene': 'ENSG00000236178'}, {'gene': 'ENSG00000137411'}, {'gene': 'ENSG00000206476'}]
VPS11 : [{'gene': 'ENSG00000280616'}, {'gene': 'ENSG00000160695'}]
VPS53 : [{'gene': 'ENSG00000141252'}, {'gene': 'ENSG00000283883'}]
WDR45 : [{'gene': 'ENSG00000196998'}, {'gene': 'ENSG00000292221'}]
WDR73 : [{'gene': 'ENSG00000177082'}, {'gene': 'ENSG00000291629'}]
WDR81 : [{'gene': 'ENSG00000167716'}, {'gene': 'ENSG00000276021'}]
XYLT1 : [{'gene': 'ENSG00000285395'}, {'gene': 'ENSG00000103489'}]
CDKN1C : [{'gene': 'ENSG00000129757'}, {'gene': 'ENSG00000273707'}]
DHRSX : [{'gene': 'ENSG00000169084'}, {'gene': 'ENSG00000292338'}]
DYNC1I2 : [{'gene': 'ENSG00000292102'}, {'gene': 'ENSG00000077380'}]
EEF1B2 : [{'gene': 'ENSG00000114942'}, {'gene': 'ENSG00000283391'}]
FDFT1 : [{'gene': 'ENSG00000284967'}, {'gene': 'ENSG00000079459'}]
GABBR1 : [{'gene': 'ENSG00000237112'}, {'gene': 'ENSG00000206511'}, {'gene': 'ENSG00000204681'}, {'gene': 'ENSG00000232632'}, {'gene': 'ENSG00000237051'}, {'gene': 'ENSG00000232569'}, {'gene': 'ENSG00000206466'}]
GLS : ['ENSG00000115419', 'ENSG00000115419']
HNF1B : [{'gene': 'ENSG00000276194'}, {'gene': 'ENSG00000275410'}]
PAM16 : [{'gene': 'ENSG00000217930'}, {'gene': 'ENSG00000282228'}]
PSMB8 : [{'gene': 'ENSG00000226201'}, {'gene': 'ENSG00000231631'}, {'gene': 'ENSG00000236443'}, {'gene': 'ENSG00000230669'}, {'gene': 'ENSG00000204264'}, {'gene': 'ENSG00000206298'}, {'gene': 'ENSG00000235715'}, {'gene': 'ENSG00000230034'}]
SLC25A26 : [{'gene': 'ENSG00000144741'}, {'gene': 'ENSG00000282739'}]
TWIST2 : [{'gene': 'ENSG00000288335'}, {'gene': 'ENSG00000233608'}]
ZFP57 : [{'gene': 'ENSG00000206510'}, {'gene': 'ENSG00000223858'}, {'gene': 'ENSG00000204644'}, {'gene': 'ENSG00000232099'}, {'gene': 'ENSG00000223852'}, {'gene': 'ENSG00000234669'}, {'gene': 'ENSG00000226858'}, {'gene': 'ENSG00000227858'}]
ABCB11 : [{'gene': 'ENSG00000073734'}, {'gene': 'ENSG00000276582'}]
ABCC6 : [{'gene': 'ENSG00000275331'}, {'gene': 'ENSG00000091262'}]
AGK : [{'gene': 'ENSG00000262327'}, {'gene': 'ENSG00000006530'}]
AKAP17A : [{'gene': 'ENSG00000292343'}, {'gene': 'ENSG00000197976'}]
ASMT : [{'gene': 'ENSG00000292336'}, {'gene': 'ENSG00000196433'}]
ASMTL : [{'gene': 'ENSG00000169093'}, {'gene': 'ENSG00000292339'}]
ATXN1 : ['ENSG00000124788', 'ENSG00000124788']
ATXN10 : ['ENSG00000130638', 'ENSG00000130638']
ATXN2 : ['ENSG00000204842', 'ENSG00000204842']
ATXN3 : ['ENSG00000066427', 'ENSG00000066427']
ATXN7 : ['ENSG00000163635', 'ENSG00000163635']
BDP1 : [{'gene': 'ENSG00000273873'}, {'gene': 'ENSG00000145734'}, {'gene': 'ENSG00000274803'}]
C9orf72 : ['ENSG00000147894', 'ENSG00000147894']
CCDC40 : [{'gene': 'ENSG00000141519'}, {'gene': 'ENSG00000291505'}]
CD99 : [{'gene': 'ENSG00000002586'}, {'gene': 'ENSG00000292348'}]
COL11A2 : [{'gene': 'ENSG00000204248'}, {'gene': 'ENSG00000223699'}, {'gene': 'ENSG00000235708'}, {'gene': 'ENSG00000227801'}, {'gene': 'ENSG00000230930'}, {'gene': 'ENSG00000232541'}, {'gene': 'ENSG00000206290'}]
COL18A1 : [{'gene': 'ENSG00000182871'}, {'gene': 'ENSG00000292234'}]
CRLF2 : [{'gene': 'ENSG00000205755'}, {'gene': 'ENSG00000292363'}]
CRYGC : [{'gene': 'ENSG00000163254'}, {'gene': 'ENSG00000285011'}]
CRYGD : [{'gene': 'ENSG00000118231'}, {'gene': 'ENSG00000285434'}]
CSF2RA : [{'gene': 'ENSG00000292357'}, {'gene': 'ENSG00000198223'}]
DCHS2 : [{'gene': 'ENSG00000284227'}, {'gene': 'ENSG00000197410'}]
DLGAP2 : [{'gene': 'ENSG00000282152'}, {'gene': 'ENSG00000274161'}, {'gene': 'ENSG00000282318'}, {'gene': 'ENSG00000198010'}, {'gene': 'ENSG00000282103'}]
DMPK : ['ENSG00000104936', 'ENSG00000104936']
DSCAM : [{'gene': 'ENSG00000291561'}, {'gene': 'ENSG00000171587'}]
ERMARD : [{'gene': 'ENSG00000276187'}, {'gene': 'ENSG00000130023'}]
FKBPL : [{'gene': 'ENSG00000223666'}, {'gene': 'ENSG00000230907'}, {'gene': 'ENSG00000204315'}, {'gene': 'ENSG00000224200'}]
FXN : ['ENSG00000165060', 'ENSG00000165060']
GAA : [{'gene': 'ENSG00000171298'}, {'gene': 'ENSG00000291507'}]
GATA4 : [{'gene': 'ENSG00000136574'}, {'gene': 'ENSG00000285109'}]
GPR179 : [{'gene': 'ENSG00000277399'}, {'gene': 'ENSG00000276469'}]
IL3RA : [{'gene': 'ENSG00000292332'}, {'gene': 'ENSG00000185291'}]
IQSEC3 : [{'gene': 'ENSG00000120645'}, {'gene': 'ENSG00000262607'}]
ITCH : [{'gene': 'ENSG00000289720'}, {'gene': 'ENSG00000078747'}]
KCND1 : [{'gene': 'ENSG00000102057'}, {'gene': 'ENSG00000292214'}]
KCNQ1 : [{'gene': 'ENSG00000282076'}, {'gene': 'ENSG00000053918'}]
KIF26B : [{'gene': 'ENSG00000162849'}, {'gene': 'ENSG00000281216'}]
MAGIX : [{'gene': 'ENSG00000292218'}, {'gene': 'ENSG00000269313'}]
MAPT : [{'gene': 'ENSG00000276155'}, {'gene': 'ENSG00000186868'}, {'gene': 'ENSG00000277956'}]
MYT1 : [{'gene': 'ENSG00000196132'}, {'gene': 'ENSG00000276876'}]
NDN : [{'gene': 'ENSG00000288364'}, {'gene': 'ENSG00000182636'}]
NDUFA11 : [{'gene': 'ENSG00000292058'}, {'gene': 'ENSG00000174886'}]
NIPA1 : [{'gene': 'ENSG00000288478'}, {'gene': 'ENSG00000170113'}]
NSF : [{'gene': 'ENSG00000276262'}, {'gene': 'ENSG00000073969'}, {'gene': 'ENSG00000278174'}]
NXF4 : ['ENSG00000290811', 'ENSG00000196970']
NXF5 : ['ENSG00000126952', 'ENSG00000290798']
P2RY8 : [{'gene': 'ENSG00000292333'}, {'gene': 'ENSG00000182162'}]
PLCXD1 : [{'gene': 'ENSG00000182378'}, {'gene': 'ENSG00000292344'}]
PNP : [{'gene': 'ENSG00000291814'}, {'gene': 'ENSG00000198805'}]
PPP2R2B : ['ENSG00000156475', 'ENSG00000156475']
PROP1 : [{'gene': 'ENSG00000274382'}, {'gene': 'ENSG00000280635'}, {'gene': 'ENSG00000175325'}]
RING1 : [{'gene': 'ENSG00000231115'}, {'gene': 'ENSG00000228520'}, {'gene': 'ENSG00000235107'}, {'gene': 'ENSG00000204227'}, {'gene': 'ENSG00000206287'}, {'gene': 'ENSG00000226788'}]
RNF135 : [{'gene': 'ENSG00000181481'}, {'gene': 'ENSG00000291712'}]
SCRIB : [{'gene': 'ENSG00000274287'}, {'gene': 'ENSG00000180900'}]
SHOX : [{'gene': 'ENSG00000185960'}, {'gene': 'ENSG00000292354'}]
SLC25A24 : [{'gene': 'ENSG00000284468'}, {'gene': 'ENSG00000085491'}]
SLC25A6 : [{'gene': 'ENSG00000169100'}, {'gene': 'ENSG00000292334'}]
TBX22 : [{'gene': 'ENSG00000122145'}, {'gene': 'ENSG00000277800'}]
TINF2 : [{'gene': 'ENSG00000092330'}, {'gene': 'ENSG00000284915'}]
TRPM1 : [{'gene': 'ENSG00000274965'}, {'gene': 'ENSG00000134160'}]
VAMP7 : [{'gene': 'ENSG00000292366'}, {'gene': 'ENSG00000124333'}]
WNT3 : [{'gene': 'ENSG00000277641'}, {'gene': 'ENSG00000277626'}, {'gene': 'ENSG00000108379'}]
YWHAE : [{'gene': 'ENSG00000274474'}, {'gene': 'ENSG00000108953'}]

In [84]:
import requests
# Query Ensembl BioMart
url = "https://rest.ensembl.org/lookup/symbol/homo_sapiens/{}?expand=0"

results = []
for gene in double_hit:
    print(gene)
    response = requests.get(url.format(gene), headers={"Content-Type": "application/json"})
    if response.ok:
        data = response.json()
        results.append({"Gene Symbol": gene, "ENSG ID": data["id"]})
    else:
        results.append({"Gene Symbol": gene, "ENSG ID": "Not Found"})

# Convert to DataFrame
df = pd.DataFrame(results)
print(df)

AAAS
ABHD16A
ACACA
ACTG1
ADGRL1
AKT3
ANO4
B3GALNT2
BRSK2
CACNA1C
CAPN15
CC2D1A
CLN3
CLN8
CNOT3
CNTNAP2
COG5
CSNK2B
CSTB
CTDP1
DEAF1
DLL1
EIF4A3
EIF5A
ERI1
FAM20C
FMR1
FTCD
GATAD2B
GCSH
GFER
HERC2
HNRNPH1
HNRNPR
HRAS
KANSL1
KAT6B
KCNQ2
KCNT2
KIF5C
LSS
MAGEL2
MASP1
MBOAT7
MCCC2
NDE1
NDUFS1
NEU1
NSDHL
OCLN
OSGEP
OTUD5
PARN
PCGF2
PEX5
PIGW
POLR2A
PQBP1
PRPF8
PTEN
SARS2
SDCCAG8
SHANK3
SLC25A12
SLC35A2
SLC6A3
SMARCB1
SMPD4
STRA6
SURF1
SYNCRIP
SYNGAP1
TAF4
TBCD
TCF20
TFE3
TRAPPC12
TRAPPC4
TSEN34
TTC5
TUBB
UBR7
VARS2
VPS11
VPS53
WDR45
WDR73
WDR81
XYLT1
CDKN1C
DHRSX
DYNC1I2
EEF1B2
FDFT1
GABBR1
GLS
HNF1B
PAM16
PSMB8
SLC25A26
TWIST2
ZFP57
ABCB11
ABCC6
AGK
AKAP17A
ASMT
ASMTL
ATXN1
ATXN10
ATXN2
ATXN3
ATXN7
BDP1
C9orf72
CCDC40
CD99
COL11A2
COL18A1
CRLF2
CRYGC
CRYGD
CSF2RA
DCHS2
DLGAP2
DMPK
DSCAM
ERMARD
FKBPL
FXN
GAA
GATA4
GPR179
IL3RA
IQSEC3
ITCH
KCND1
KCNQ1
KIF26B
MAGIX
MAPT
MYT1
NDN
NDUFA11
NIPA1
NSF
NXF4
NXF5
P2RY8
PLCXD1
PNP
PPP2R2B
PROP1
RING1
RNF135
SCRIB
SHOX
SLC25A24
SLC25A6
TBX22
TINF2
TRPM1
VAMP7
WNT3
YWHAE
    Gene Symbol          ENSG ID
0          AAAS  ENSG00000094914
1       ABHD16A  ENSG00000204427
2         ACACA  ENSG00000278540
3         ACTG1  ENSG00000184009
4        ADGRL1  ENSG00000072071
..          ...              ...
160       TINF2  ENSG00000092330
161       TRPM1  ENSG00000134160
162       VAMP7  ENSG00000292366
163        WNT3  ENSG00000108379
164       YWHAE  ENSG00000108953

[165 rows x 2 columns]

In [87]:
for i in range(len(df)):
    dup_dict[df["Gene Symbol"][i]]=df["ENSG ID"][i]

In [65]:
#no hit genes
no_hit

['AARS',
 'APOPT1',
 'ARSE',
 'C12ORF65',
 'C5ORF42',
 'CXORF56',
 'DARS',
 'FAM126A',
 'H3F3B',
 'HIST1H4C',
 'HIST1H4E',
 'IARS',
 'ISPD',
 'KARS',
 'KIAA1109',
 'KIF1BP',
 'LARS',
 'MPP5',
 'MTSS1L',
 'NARS',
 'QARS',
 'RARS',
 'SARS',
 'SPATA5',
 'SPATA5L1',
 'TMEM5',
 'TTC37',
 'ADPRHL2',
 'ARMC4',
 'C16ORF62',
 'C8ORF37',
 'FUK',
 'HARS',
 'HIST1H4I',
 'MKL2',
 'C20ORF24',
 'C2ORF71',
 'C3ORF58',
 'C4ORF26',
 'CCDC114',
 'CTGF',
 'DDX58',
 'DSCR3',
 'FAM160B1',
 'FAM58A',
 'HIST1H4B',
 'HIST1H4D',
 'HIST1H4F',
 'HIST3H3',
 'LRRC6',
 'WDR34',
 'WDR60']

In [67]:
#no hit genes
#some were repeated from before so we will deal with the same way- IARS,SARS,AARS,HIST1H4C,KIF1BP,SPATA5L1,NARS
#others - i went through each one to get this lists:

NEW_GENE_NAME=['AARS1','COA8','ARSL','MTRFR','CPLANE1','STEEP1','DASR1','HYCC1','H4C3','H3-3B','H4C5','IARS1','CRPPA',
               'KARS1','BLTP1','KIF1BP','PTPRF','PALS1','MTSS2','NARS1','QARS1','RARS1','SARS1','AFG2A','AFG2B','RXYLT1',
               'SKIC3','ADPRS','ODAD2','C16ORF62','CFAP418','FCSK','HARS1','H4C9','MRTFB','RAB5IF','PCARE','DIPK2A',
               'ODAPH','ODAD1','CCN2','RIGI','VPS26C','FHIP2A','CCNQ','HIST1H4B','H4CD','H4C6','HIST3H3','DNAAF11',
               'DYNC2I2','DYNC2I1']
NEW_ENS=['ENSG00000090861','ENSG00000256053','ENSG00000157399','ENSG00000130921','ENSG00000197603','ENSG00000018610',
         'ENSG00000115866','ENSG00000122591','ENSG00000197061','ENSG00000132475','ENSG00000276966','ENSG00000196305',
         'ENSG00000214960','ENSG00000065427','ENSG00000138688','ENSG00000304022','ENSG00000142949','ENSG00000072415',
         'ENSG00000132613','ENSG00000172053','ENSG00000134440','ENSG00000113643','ENSG00000031698','ENSG00000145375',
         'ENSG00000171763','ENSG00000118600','ENSG00000198677','ENSG00000116863','ENSG00000169126','ENSG00000276571',
         'ENSG00000156172','ENSG00000157353','ENSG00000170445','ENSG00000276180','ENSG00000186260','ENSG00000101084',
         'ENSG00000179270','ENSG00000181744','ENSG00000174792','ENSG00000105479','ENSG00000118523','ENSG00000107201',
         'ENSG00000157538','ENSG00000151553','ENSG00000262919','ENSG00000295483','ENSG00000277157','ENSG00000274618',
         'ENSG00000271230','ENSG00000129295','ENSG00000119333','ENSG00000126870']

print(len(no_hit))
print(len(NEW_GENE_NAME))
print(len(NEW_ENS))

52
52
52

In [91]:
id_df=pd.DataFrame({'gene':dup_dict.keys(),'ens':dup_dict.values()})
id_df

         gene                ens
0        AAAS    ENSG00000094914
1        AARS                 []
2        AASS  [ENSG00000008311]
3        ABAT  [ENSG00000183044]
4       ABCA2  [ENSG00000107331]
...       ...                ...
2710   ZNF713  [ENSG00000178665]
2711    ZNF81  [ENSG00000197779]
2712    KIF5B  [ENSG00000170759]
2713  ZMYND15  [ENSG00000141497]
2714  C12ORF4  [ENSG00000047621]

[2715 rows x 2 columns]

In [100]:
for i in range(len(no_hit)):
    id_df.loc[id_df.gene==no_hit[i],'ens']=NEW_ENS[i]
    id_df.loc[id_df.gene==no_hit[i],'gene']=NEW_GENE_NAME[i]
id_df

         gene                ens
0        AAAS    ENSG00000094914
1       AARS1    ENSG00000090861
2        AASS  [ENSG00000008311]
3        ABAT  [ENSG00000183044]
4       ABCA2  [ENSG00000107331]
...       ...                ...
2710   ZNF713  [ENSG00000178665]
2711    ZNF81  [ENSG00000197779]
2712    KIF5B  [ENSG00000170759]
2713  ZMYND15  [ENSG00000141497]
2714  C12ORF4  [ENSG00000047621]

[2715 rows x 2 columns]

In [107]:
#fix list to str format
for i in range(len(id_df)):
    if type(id_df.ens[i]) is list:
        id_df.iloc[i,1]=str(id_df.iloc[i,1])[2:-2]
id_df

         gene              ens
0        AAAS  ENSG00000094914
1       AARS1  ENSG00000090861
2        AASS  ENSG00000008311
3        ABAT  ENSG00000183044
4       ABCA2  ENSG00000107331
...       ...              ...
2710   ZNF713  ENSG00000178665
2711    ZNF81  ENSG00000197779
2712    KIF5B  ENSG00000170759
2713  ZMYND15  ENSG00000141497
2714  C12ORF4  ENSG00000047621

[2715 rows x 2 columns]

In [112]:
for i in range(len(id_df)):
    if len(id_df.ens[i])!=15:
        print(id_df.iloc[i,:])

gene    C12orf4
ens
Name: 176, dtype: object
gene    C12orf65
ens
Name: 178, dtype: object
gene    C5orf42
ens
Name: 181, dtype: object
gene    CXorf56
ens
Name: 319, dtype: object
gene    C16orf62
ens
Name: 1474, dtype: object
gene    C8orf37
ens
Name: 1475, dtype: object
gene    C20orf24
ens
Name: 1863, dtype: object
gene    C2orf71
ens
Name: 1864, dtype: object
gene    C3orf58
ens
Name: 1865, dtype: object
gene    C4orf26
ens
Name: 1866, dtype: object

In [113]:
to_fix=['C12orf4','C12orf65','C5orf42','CXorf56','C16orf62','C8orf37','C20orf24','C2orf71',' C3orf58','C4orf26']
new_name=['FERRY3','MTRFR','CPLANE1','STEEP1','C16orf62','CFAP418','RAB5IF','PCARE','DIPK2A','ODAPH']
new_ens=['ENSG00000047621','ENSG00000130921','ENSG00000197603','ENSG00000018610','ENSG00000276571','ENSG00000156172',
         'ENSG00000101084','ENSG00000179270','ENSG00000181744','ENSG00000174792']

In [122]:
for i in range(len(to_fix)):
   id_df.loc[id_df.gene==to_fix[i],'ens']=new_ens[i]
   id_df.loc[id_df.gene==to_fix[i],'gene']=new_name[i]

In [121]:
id_df=id_df.drop_duplicates(subset=['ens'])
id_df

         gene              ens
0        AAAS  ENSG00000094914
1       AARS1  ENSG00000090861
2        AASS  ENSG00000008311
3        ABAT  ENSG00000183044
4       ABCA2  ENSG00000107331
...       ...              ...
2709   ZNF674  ENSG00000251192
2710   ZNF713  ENSG00000178665
2711    ZNF81  ENSG00000197779
2712    KIF5B  ENSG00000170759
2713  ZMYND15  ENSG00000141497

[2714 rows x 2 columns]

In [123]:
id_df.to_csv("/scratch200/reutj/data/id_list_updated.csv")

In [124]:
#to gmt
output_file="/scratch200/reutj/data/hsg_gene_lists/id_list_updated.gmt"
with open(output_file, 'w') as f:
    # Create a line in GMT format for one gene set
    line = f"id_genes\tDescription\t{'\t'.join(id_df.gene.tolist())}\n"
    f.write(line)

## autism genes

In [19]:
#autism genes

autism=pd.read_csv("/scratch200/reutj/data/SFARI-Gene_genes_01-13-2025release_02-17-2025export.csv")

In [18]:
autism

,status,gene-symbol,gene-name,ensembl-id,chromosome,genetic-category,gene-score,syndromic,eagle,number-of-reports
0,9,ABAT,4-aminobutyrate aminotransferase,ENSG00000183044,16,"Rare Single Gene Mutation, Genetic Association",2.0,0,NaN,8
1,9,ABCA10,"ATP-binding cassette, sub-family A (ABC1), mem...",ENSG00000154263,17,Rare Single Gene Mutation,2.0,0,NaN,4
2,9,ABCA13,ATP binding cassette subfamily A member 13,ENSG00000179869,7,"Rare Single Gene Mutation, Functional",2.0,0,NaN,12
3,9,ABCA2,ATP binding cassette subfamily A member 2,ENSG00000107331,9,Rare Single Gene Mutation,3.0,0,NaN,8
4,9,ABCA7,"ATP-binding cassette, sub-family A (ABC1), mem...",ENSG00000064687,19,Rare Single Gene Mutation,2.0,0,NaN,6
...,...,...,...,...,...,...,...,...,...,...
1214,9,ZNF774,Zinc finger protein 774,ENSG00000196391,15,Rare Single Gene Mutation,2.0,0,NaN,4
1215,9,ZNF804A,Zinc finger protein 804A,ENSG00000170396,2,"Rare Single Gene Mutation, Genetic Association...",2.0,0,NaN,16
1216,9,ZNF827,Zinc finger protein 827,ENSG00000151612,4,"Rare Single Gene Mutation, Genetic Association",2.0,0,NaN,3
1217,9,ZSWIM6,zinc finger SWIM-type containing 6,ENSG00000130449,5,"Rare Single Gene Mutation, Syndromic, Genetic ...",S,1,NaN,6
1218,9,ZWILCH,zwilchkinetochore protein,ENSG00000174442,15,Rare Single Gene Mutation,2.0,0,NaN,5

In [ ]:
#we notice we have gene score nan - those stand for syndromic diseases with augism so will replace nana with s
#and convert to caterogical column

In [21]:
autism["gene-score"]=autism["gene-score"].astype(str)

In [27]:
autism.loc[autism["gene-score"]=="nan","gene-score"]="S"
autism.loc[autism["gene-score"]=="1.0","gene-score"]="1"
autism.loc[autism["gene-score"]=="2.0","gene-score"]="2"
autism.loc[autism["gene-score"]=="3.0","gene-score"]="3"

In [30]:
autism["gene-score"]=autism["gene-score"].astype('category')

In [ ]:
#for the updated list, just keep ens, gene and gene-score and rename accordingly

In [31]:
autism_update=autism.loc[:,['ensembl-id','gene-symbol','gene-score']]

In [33]:
autism_update=autism_update.rename(columns={'ensembl-id':'ens','gene-symbol':'gene'})

In [34]:
autism_update.to_csv("/scratch200/reutj/data/hsg_gene_lists/autism_genes.csv")

In [35]:
#to gmt
output_file="/scratch200/reutj/data/hsg_gene_lists/autism_genes.gmt"
with open(output_file, 'w') as f:
    # Create a line in GMT format for one gene set
    line = f"autism_genes\tDescription\t{'\t'.join(autism_update.gene.tolist())}\n"
    f.write(line)

* note that autism gene scores are united here maybe saperating them into categories can help get more precise results. lets get just hose with gene_score 1

In [36]:
autism_strong=autism_update[autism_update["gene-score"]=="1"]

In [37]:
autism_strong.to_csv("/scratch200/reutj/data/hsg_gene_lists/autism_strong.csv")

In [38]:
#to gmt
output_file="/scratch200/reutj/data/hsg_gene_lists/autism_strong.gmt"
with open(output_file, 'w') as f:
    # Create a line in GMT format for one gene set
    line = f"strong_autism_genes\tDescription\t{'\t'.join(autism_strong.gene.tolist())}\n"
    f.write(line)